Flat configuration directory hierarchy
netsec-ethz/scionlab pull request #308
Opened 2020-09-29 12:00 UTC by matzf

* Add file hashes and systemd service list to `scionlab-config.json`
* Create flatter configuration directory hierachy (see #307)
* Adapt `scionlab-config` to the new config tar. Will now prompt the user before overwriting locally modified files. At the same time, remove some most likely unused functionality (`--config-info` flag)

This is an API breaking change, i.e. current `scionlab-config` scripts will not be able to properly consume the new `tar`-file.
Thusly, bumping the (global) API version to `v3`. Keeping a redirect for the unaffected `topology` API.

Closes #307

2020-10-07 08:45 UTC, FR4NK-W requested changes
> Reviewed 10 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/308)* status: 10 of 19 files reviewed, 6 unresolved discussions (waiting on @matzf)

___
*[flake8.ini, line 8 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ14pIx0tOcdSpyorsD:-MJ14pIy-4_f9wXpOeB8:b-tren0o) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/flake8.ini#L8)):*
> ```INI
>   scionlab/settings/production.py
> filename =
>   *.py
> ```

Why are those files excluded?
I don't see a reason for it, and running flake on them also does not show errors.
___
*[scionlab/config_tar.py, line 21 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ15fw18vzq3XkxBYGu:-MJ15fw18vzq3XkxBYGv:bqrgkg3) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/scionlab/config_tar.py#L21)):*
> ```
> generate_scion_config_systemd
> ```
Could we rename those to `generate_scion_systemd_config` or even `generate_systemd_config`? (For consistency with `generate_vpn_client_config` etc.)
___
*[scionlab/config_tar.py, line 130 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ17dhW0X6_lGiZBSAH:-MJ17dhW0X6_lGiZBSAI:b-yoru1i) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/scionlab/config_tar.py#L130)):*
> ```
> vpn_dir = OPENVPN_CONFIG_DIR.lstrip("/")
> ```
Why lstrip?
Do we want to have this as relative path?

Later `vpn_dir` is joined with "/server.conf", was rstrip meant?
___
*[scionlab/config_tar.py, line 178 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ18bMVAJqYeXL00VfZ:-MJ18bMVAJqYeXL00Vf_:b-23y69a) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/scionlab/config_tar.py#L178)):*
> ```
> containing the authentication parameters for the host
> ```
And the hashes and more.
Could you add a short description to the PR, explaining why and how this is used?
___
*[scionlab/scion/config.py, line 78 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ16XKXAoWICSJ-TURd:-MJ16XKXAoWICSJ-TURe:b9scf2a) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/scionlab/scion/config.py#L78)):*
> ```
> with_sig_dummy_entry=False
> ```
Could we have True as default value?
I can't see a drawback in having this entry by default.
___
*[scionlab/util/archive.py, line 228 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ1Dd2YAJRDtoviIepx:-MJ1Dd2Z4h9iOLHgmcOs:b-qrb3qn) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/scionlab/util/archive.py#L228)):*
> ```
> _normalize_path
> ```

Actually, _normalize_path is only guaranteed to stringify the path, right?
PurePosixPath are hashable. Maybe I'm missing what the intention for _normalize_path was.


<!-- Sent from Reviewable.io -->

2020-10-07 09:07 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/308)* status: 10 of 19 files reviewed, 6 unresolved discussions (waiting on @FR4NK-W and @matzf)

___
*[flake8.ini, line 8 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ14pIx0tOcdSpyorsD:-MJ1EjGn8GQ7bU_G6MUN:bbdkzq5) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/flake8.ini#L8)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

Why are those files excluded?
I don't see a reason for it, and running flake on them also does not show errors.
</blockquote></details>

That's a misunderstanding; the `filename` directive defines files to be checked. It defaults to `*.py`; I want to additionally check some file, so I specify the default + `scionlab-config`.
___
*[scionlab/config_tar.py, line 21 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ15fw18vzq3XkxBYGu:-MJ1J7XV7mFwPBPa7wmr:bhy9ot6) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/scionlab/config_tar.py#L21)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

> ```
> generate_scion_config_systemd
> ```
Could we rename those to `generate_scion_systemd_config` or even `generate_systemd_config`? (For consistency with `generate_vpn_client_config` etc.)
</blockquote></details>

Will do.
___
*[scionlab/config_tar.py, line 130 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ17dhW0X6_lGiZBSAH:-MJ1Hf_g2VlIaQh4as_c:bo2a1sj) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/scionlab/config_tar.py#L130)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

> ```
> vpn_dir = OPENVPN_CONFIG_DIR.lstrip("/")
> ```
Why lstrip?
Do we want to have this as relative path?

Later `vpn_dir` is joined with "/server.conf", was rstrip meant?
</blockquote></details>

Yes, the paths in the archive need to be relative (to the archive root). So the paths are all `etc/scion/foo.toml` and `etc/openvpn/server.conf` etc.
I admit it's not super clear, but I don't know a better way. I can at least add a comment to the `lstrip`, I guess. There is another place that does the same thing with the comment "dont use absolute paths in the archive" -- is this clear enough?
___
*[scionlab/config_tar.py, line 178 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ18bMVAJqYeXL00VfZ:-MJ1J38bA2nuOpiEuR9l:bhy9ot6) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/scionlab/config_tar.py#L178)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

> ```
> containing the authentication parameters for the host
> ```
And the hashes and more.
Could you add a short description to the PR, explaining why and how this is used?
</blockquote></details>

Will do.
___
*[scionlab/scion/config.py, line 78 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ16XKXAoWICSJ-TURd:-MJ1GoWA0jlQJWPxTA7w:b-509odm) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/scionlab/scion/config.py#L78)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

> ```
> with_sig_dummy_entry=False
> ```
Could we have True as default value?
I can't see a drawback in having this entry by default.
</blockquote></details>

This has not been changed in this PR. The default value also doesn't really matter, it's explicitly set on every call site anyway -- it's kind of a poor mans type annotation ;)
___
*[scionlab/util/archive.py, line 228 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ1Dd2YAJRDtoviIepx:-MJ1G253AAoSgeiVxnh_:b-1sikkv) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/scionlab/util/archive.py#L228)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

> ```
> _normalize_path
> ```

Actually, _normalize_path is only guaranteed to stringify the path, right?
PurePosixPath are hashable. Maybe I'm missing what the intention for _normalize_path was.
</blockquote></details>

`_normalize_path` implements this:
```
    Note: for convenience, the `path` passed to any of the `write_`-methods can be:
        - a string
        - a pathlib.Path
        - or a tuple consisting of string/pathlib.Path that will be joined
```
It's not strictly necessary here, but it's convenient later to have all the entries in `hashes` have a key of the same type, regardless of how the `write_...` function was called.


<!-- Sent from Reviewable.io -->

2020-10-07 09:39 UTC, FR4NK-W requested changes
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/308)* status: 10 of 19 files reviewed, 4 unresolved discussions (waiting on @matzf)

___
*[scionlab/config_tar.py, line 130 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ17dhW0X6_lGiZBSAH:-MJ1NPUA0rZ1J5KSVHX7:b6z89dr) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/scionlab/config_tar.py#L130)):*
>"dont use absolute paths in the archive"

Yes, I had seen that one.

But I was surprised that vpn_dir gets joined with `"/server.conf"`, since if `OPENVPN_CONFIG_DIR` already ends with a path separator, and since it already is a string, it won't get "normalized" by _normalize_path, so we get a hash index of "/etc/openvpn//server.conf".
I guess what I'm trying to say, is that I was expecting a `vpn_dir.strip("/")` given the way the path segments are joined.
___
*[scionlab/util/archive.py, line 228 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ1Dd2YAJRDtoviIepx:-MJ1PKR-33ZxQm1nvjv3:bfymijd) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/scionlab/util/archive.py#L228)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

`_normalize_path` implements this:
```
    Note: for convenience, the `path` passed to any of the `write_`-methods can be:
        - a string
        - a pathlib.Path
        - or a tuple consisting of string/pathlib.Path that will be joined
```
It's not strictly necessary here, but it's convenient later to have all the entries in `hashes` have a key of the same type, regardless of how the `write_...` function was called.
</blockquote></details>

I agree that all entries in `hashes` should have a key of the same type.

What is relevant here, I think, is that `_normalize_path` only normalizes to string and does not always do the path normalization `PurePosixPath` does, namely when called with a string.
So one could have multiple keys for `dir_name/file`, `dif_name//file` depending on how the `write_...`function was called, which, as you point out, is one of the things `_normalize_path`tries to prevent.


<!-- Sent from Reviewable.io -->

2020-10-07 09:41 UTC, juagargi requested changes
> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/308)* status: all files reviewed, 9 unresolved discussions (waiting on @matzf)

___
*[flake8.ini, line 3 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MIy8Q3F4y9h_2XHVVTd:-MIy8Q3F4y9h_2XHVVTe:b-bvv0td) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/flake8.ini#L3)):*
> ```INI
> [flake8]
> exclude =
>   env
> ```

can we also add `venv` and `.venv` like we have in `.gitignore` ?
___
*[scionlab/hostfiles/scionlab-config, line 338 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ1ACgPE4cu-0qbS6zp:-MJ1ACgPE4cu-0qbS6zq:bmbg9yw) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/scionlab/hostfiles/scionlab-config#L338)):*
> ```
> 
>     if args.force:
>         skip = []
> ```

what is the plan for when a `deb` package is updated and there is a file with a difference?
___
*[scionlab/hostfiles/scionlab-config, line 412 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ1MqsHDKTXkvFRYDKa:-MJ1MqsHDKTXkvFRYDKb:b-7xhrqz) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/scionlab/hostfiles/scionlab-config#L412)):*
> ```
> 
> 
> def extract_files(tar, files, tmpdir):
> ```

function is unused.
___
*[scionlab/hostfiles/scionlab-config, line 461 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ1OLmi0yyPdU6wC9xZ:-MJ1OLmi0yyPdU6wC9x_:b-u46myf) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/scionlab/hostfiles/scionlab-config#L461)):*
> ```
> 
> def run_scion():
>     subprocess.run(['systemctl', 'restart', 'scionlab.target'], check=True)
> ```

I should remember, but I don't: why is it that we restart `scionlab.target` instead of just starting it? it seems we always stop it before calling this function.
___
*[scionlab/scion/config.py, line 422 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MIzAOqi4NB36fZZzCAu:-MIzAOqi4NB36fZZzCAv:b-lstsxv) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/scionlab/scion/config.py#L422)):*
> ```Python
> 
> 
> def _localhost(ip):
> ```

the function seems unused.


<!-- Sent from Reviewable.io -->

2020-10-07 13:50 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/308)* status: 13 of 21 files reviewed, 9 unresolved discussions (waiting on @FR4NK-W and @juagargi)

___
*[flake8.ini, line 3 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MIy8Q3F4y9h_2XHVVTd:-MJ1SY5rEFDHPODC_6uA:bkzjeqd) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/flake8.ini#L3)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

can we also add `venv` and `.venv` like we have in `.gitignore` ?
</blockquote></details>

Done. Added all spelling variants from gitignore.
Btw, also renamed the file to the "proper" name `.flake8`, so it will be picked up by default without specifying `--config`.
___
*[scionlab/config_tar.py, line 21 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ15fw18vzq3XkxBYGu:-MJ20VjUDhdvYxha7i0j:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/scionlab/config_tar.py#L21)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

Done.
___
*[scionlab/config_tar.py, line 130 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ17dhW0X6_lGiZBSAH:-MJ20n2V6g5PTHdbFBeu:bjvbvw5) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/scionlab/config_tar.py#L130)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

>"dont use absolute paths in the archive"

Yes, I had seen that one.

But I was surprised that vpn_dir gets joined with `"/server.conf"`, since if `OPENVPN_CONFIG_DIR` already ends with a path separator, and since it already is a string, it won't get "normalized" by _normalize_path, so we get a hash index of "/etc/openvpn//server.conf".
I guess what I'm trying to say, is that I was expecting a `vpn_dir.strip("/")` given the way the path segments are joined.
</blockquote></details>

`OPENVPN_CONFIG_DIR` does not end with a separator (?).
Anyway, to avoid the legitimate confusion, I'm now just joining the paths properly.
Done.
___
*[scionlab/config_tar.py, line 178 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ18bMVAJqYeXL00VfZ:-MJ2FtXC5tKwEU_gmlle:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/scionlab/config_tar.py#L178)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

Done.
___
*[scionlab/hostfiles/scionlab-config, line 338 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ1ACgPE4cu-0qbS6zp:-MJ23HOI7kBbH3pRhycB:b-p1knq9) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/scionlab/hostfiles/scionlab-config#L338)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

what is the plan for when a `deb` package is updated and there is a file with a difference?
</blockquote></details>

Hmmm... good question, hadn't thought about that. What would be good? Create a backup of conflicted files?
___
*[scionlab/hostfiles/scionlab-config, line 412 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ1MqsHDKTXkvFRYDKa:-MJ23R-h6IADJDaciRI9:b-y01cq2) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/scionlab/hostfiles/scionlab-config#L412)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

function is unused.
</blockquote></details>

Thanks, done. 
___
*[scionlab/hostfiles/scionlab-config, line 461 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ1OLmi0yyPdU6wC9xZ:-MJ23w6W95hk7VmeL5rP:bmbkmcf) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/scionlab/hostfiles/scionlab-config#L461)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

I should remember, but I don't: why is it that we restart `scionlab.target` instead of just starting it? it seems we always stop it before calling this function.
</blockquote></details>

I have no clue either, might be historical. Changed it to `start`.
___
*[scionlab/scion/config.py, line 422 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MIzAOqi4NB36fZZzCAu:-MJ24MU20kS6axEDzgx3:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/scionlab/scion/config.py#L422)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

the function seems unused.
</blockquote></details>

Done.
___
*[scionlab/util/archive.py, line 228 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ1Dd2YAJRDtoviIepx:-MJ2C1We65wm2VGKFtRG:b5e6cvk) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/scionlab/util/archive.py#L228)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

I agree that all entries in `hashes` should have a key of the same type.

What is relevant here, I think, is that `_normalize_path` only normalizes to string and does not always do the path normalization `PurePosixPath` does, namely when called with a string.
So one could have multiple keys for `dir_name/file`, `dif_name//file` depending on how the `write_...`function was called, which, as you point out, is one of the things `_normalize_path`tries to prevent.
</blockquote></details>

Ah I see what you mean. :+1:  Fixed. 


<!-- Sent from Reviewable.io -->

2020-10-07 14:34 UTC, juagargi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-:-MJ2TAPE5uA00-HUpmLz:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @FR4NK-W)

___
*[flake8.ini, line 3 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MIy8Q3F4y9h_2XHVVTd:-MJ2SscZEbSyKvZbA5Ws:bkj3yzo) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/flake8.ini#L3)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Done. Added all spelling variants from gitignore.
Btw, also renamed the file to the "proper" name `.flake8`, so it will be picked up by default without specifying `--config`.
</blockquote></details>

I can now configure my VSCode's flake8 without arguments! :tada: 
___
*[scionlab/hostfiles/scionlab-config, line 338 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ1ACgPE4cu-0qbS6zp:-MJ2T1kv1YhU0Ze12SLP:b-j7tx7w) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/scionlab/hostfiles/scionlab-config#L338)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Hmmm... good question, hadn't thought about that. What would be good? Create a backup of conflicted files?
</blockquote></details>

I think the backup is a great idea.


<!-- Sent from Reviewable.io -->

2020-10-07 15:36 UTC, FR4NK-W requested changes
> Reviewed 6 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/308)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[scionlab/hostfiles/scionlab-config, line 153 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ2eZjqAvzXtc-QAc8f:-MJ2eZjqAvzXtc-QAc8g:b-yc4h8z) ([raw file](https://github.com/netsec-ethz/scionlab/blob/d9a1a28f80629c31eb14233d6d095f351790261e/scionlab/hostfiles/scionlab-config#L153)):*
> ```
> 3.0, api/v3
> ```

Might be worth it to have version and API version as a variable at the beginning, to make editing this file and forgetting to update the version string less likely.
___
*[scionlab/hostfiles/scionlab-config, line 359 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ2gMzV1MDYAIpSb37-:-MJ2gMzV1MDYAIpSb370:bnyu9gm) ([raw file](https://github.com/netsec-ethz/scionlab/blob/d9a1a28f80629c31eb14233d6d095f351790261e/scionlab/hostfiles/scionlab-config#L359)):*
> ```
> shutil.rmtree(os.path.join(SCION_CONFIG_PATH, 'gen'), ignore_errors=True)
> ```
We should show the prompt, asking if the user wants to remove that directory recursively, even though it is outdated.
___
*[scionlab/hostfiles/scionlab-config, line 364 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ2fcAK5xGxz6_h8I6G:-MJ2fcAK5xGxz6_h8I6H:b-cffxcd) ([raw file](https://github.com/netsec-ethz/scionlab/blob/d9a1a28f80629c31eb14233d6d095f351790261e/scionlab/hostfiles/scionlab-config#L364)):*
> ```
> save
> ```
safe


<!-- Sent from Reviewable.io -->

2020-10-07 19:01 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/308)* status: 19 of 21 files reviewed, 1 unresolved discussion (waiting on @FR4NK-W and @juagargi)

___
*[scionlab/hostfiles/scionlab-config, line 338 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ1ACgPE4cu-0qbS6zp:-MJ3R7aW9clx6Ca6COPa:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/2b123c839a74acb47dec02e5d28bdfc8b02ad8fe/scionlab/hostfiles/scionlab-config#L338)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

I think the backup is a great idea.
</blockquote></details>

Done.
___
*[scionlab/hostfiles/scionlab-config, line 359 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ2gMzV1MDYAIpSb37-:-MJ2joi88m3CYO4QUYZA:b-qx9ztn) ([raw file](https://github.com/netsec-ethz/scionlab/blob/d9a1a28f80629c31eb14233d6d095f351790261e/scionlab/hostfiles/scionlab-config#L359)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

> ```
> shutil.rmtree(os.path.join(SCION_CONFIG_PATH, 'gen'), ignore_errors=True)
> ```
We should show the prompt, asking if the user wants to remove that directory recursively, even though it is outdated.
</blockquote></details>

We've always been trampling all over this directory, I don't see why we should suddenly be careful. Note that this will most likely happen only once during the package update (where we can't prompt).


<!-- Sent from Reviewable.io -->

2020-10-07 19:04 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/308)* status: 19 of 21 files reviewed, 1 unresolved discussion (waiting on @FR4NK-W and @juagargi)

___
*[scionlab/hostfiles/scionlab-config, line 153 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ2eZjqAvzXtc-QAc8f:-MJ3Rjl07YnrfHPl5Fqq:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/d9a1a28f80629c31eb14233d6d095f351790261e/scionlab/hostfiles/scionlab-config#L153)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

> ```
> 3.0, api/v3
> ```

Might be worth it to have version and API version as a variable at the beginning, to make editing this file and forgetting to update the version string less likely.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-08 12:28 UTC, FR4NK-W approved these changes
> Reviewed 6 of 19 files at r1, 1 of 8 files at r2, 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/308)* status: 20 of 21 files reviewed, all discussions resolved (waiting on @FR4NK-W and @juagargi)

___
*[scionlab/scion/config.py, line 115 at r3](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ6JCyv5SswWOVCx9CR:-MJ6JCyv5SswWOVCx9CS:brvsbv) ([raw file](https://github.com/netsec-ethz/scionlab/blob/500e7953fdada490e9f3197705ead646689c7c1f/scionlab/scion/config.py#L115)):*
> ```
> _write_beacon_policy
> ```

One thing hadn't realized, is that with the flat dir structure we give up the possibility to have a different beaconing policy per _control_services (not that it was used in the current deployment, just in case we come back and do actually make use of non-global policies).


<!-- Sent from Reviewable.io -->

2020-10-08 13:10 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/308)* status: 20 of 21 files reviewed, all discussions resolved (waiting on @FR4NK-W and @juagargi)

___
*[scionlab/scion/config.py, line 115 at r3](https://reviewable.io/reviews/netsec-ethz/scionlab/308#-MJ6JCyv5SswWOVCx9CR:-MJ7JTdW35S1g5wZSYOQ:b-51tegr) ([raw file](https://github.com/netsec-ethz/scionlab/blob/500e7953fdada490e9f3197705ead646689c7c1f/scionlab/scion/config.py#L115)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

> ```
> _write_beacon_policy
> ```

One thing hadn't realized, is that with the flat dir structure we give up the possibility to have a different beaconing policy per _control_services (not that it was used in the current deployment, just in case we come back and do actually make use of non-global policies).
</blockquote></details>

No, that's not correct. The file path to the policy file is defined in the control service toml file. We can have several different of these policy files. Btw, even for a single CS, there can be up to three different policy files, origination, propagation and registration -- it's a bit over-complicated tbh.


<!-- Sent from Reviewable.io -->

2020-10-08 19:27 UTC, merged