Extension of SCIONLab project with Pull Attachment Point feature
netsec-ethz/scionlab pull request #313
Opened 2020-11-03 11:13 UTC by fl99kl

- added daemon mode to scionlab-config script

- added service file to start daemon mode

- updated AttachmentPoint model to contain a DateTimeField (timestamps will be updated in api called by scionlab-config script)

- deleted SSH features (push APs)

2020-11-03 12:44 UTC, matzf reviewed
> Reviewed 18 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/313)* status: all files reviewed, 15 unresolved discussions (waiting on @fl99kl)

___
*[.circleci/config.yml, line 66 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLCqg9465J1b6qOL0-E:-MLCqg9465J1b6qOL0-F:b-g3hv45) ([raw file](https://github.com/netsec-ethz/scionlab/blob/ec947461c953f265b9bf4007d0eeb7426be9f535/.circleci/config.yml#L66)):*
> ```YAML
>       cp .circleci/setup/deploy_rsa* run/ && \
>       chmod 644 run/deploy_rsa.pub && \
>       chmod 600 run/deploy_rsa'
> ```

Everything after `init-test-db.sh` should be removed here.
___
*[.circleci/config.yml, line 195 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLD7IgF0LlI1SQjeQ81:-MLD7IgF0LlI1SQjeQ82:b-ssxbks) ([raw file](https://github.com/netsec-ethz/scionlab/blob/82235c720d0783645e1312f9f720c9dc034c5fa7/.circleci/config.yml#L195)):*
> ```YAML
> 
>       - run:
>           name: "Push changes to AS ffaa:0:1303"
> ```

Would be nice to keep this test and just change it to "Pull" instead.
___
*[.circleci/config.yml, line 207 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLD6ehv-902ncIfxYoA:-MLD6ehv-902ncIfxYoB:bns91cb) ([raw file](https://github.com/netsec-ethz/scionlab/blob/ec947461c953f265b9bf4007d0eeb7426be9f535/.circleci/config.yml#L207)):*
> ```YAML
>             docker-compose exec -T coord /bin/bash -c \
>              'python .circleci/actions/update-keys.py --core-keys ffaa:0:1301;
>               python .circleci/actions/push-deploy.py ffaa:0:1301 ffaa:0:1303 ffaa:0:1305'
> ```

More push deploy here.
Needs to be changed to a `pull`, something along the lines of `docker-compose exec -T as1301 scionlab-config`.
___
*[.circleci/config.yml, line 209 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLCr1_p3Vi_yWC8DC9v:-MLCr1_p3Vi_yWC8DC9w:b9fvrc3) ([raw file](https://github.com/netsec-ethz/scionlab/blob/ec947461c953f265b9bf4007d0eeb7426be9f535/.circleci/config.yml#L209)):*
> ```
> huey
> ```
This is gone.
Btw, remove `huey` from `.circleci/docker-compose.yml` and `docker-compose.yml`.
___
*[.circleci/Dockerfile-scionHost, line 30 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLD7Vb27AiLqHP3jsRK:-MLD7Vb27AiLqHP3jsRL:b-ah59zg) ([raw file](https://github.com/netsec-ethz/scionlab/blob/ec947461c953f265b9bf4007d0eeb7426be9f535/.circleci/Dockerfile-scionHost#L30)):*
> ```
> RUN apt-get update && apt-get install --assume-yes scionlab
> 
> # Add 'scionlab' user with passwordless sudo & configure authorized_keys to allow automatic deployment
> ```

Remove left over comment ("& configure authorized_keys ...")
___
*[scionlab/forms/attachment_conf_form.py, line 312 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLCrgdR0RppHZsPRmmI:-MLCrgdR0RppHZsPRmmJ:b9zymnw) ([raw file](https://github.com/netsec-ethz/scionlab/blob/ec947461c953f265b9bf4007d0eeb7426be9f535/scionlab/forms/attachment_conf_form.py#L312)):*
> ```Python
>         self.helper = AttachmentConfFormHelper(instance, userAS)
>         super().__init__(*args, initial=initial, **kwargs)
>         self.fields['attachment_point'].queryset = AttachmentPoint.objects.active()
> ```

Lets leave this change (and the related change above in the same file) for the separate PR with the user AP feature, ok?
___
*[scionlab/hostfiles/scionlab-config, line 82 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLCsJRd6jnxry-IY7nd:-MLCsJRe-oKf-OiJpsx_:b5aj9it) ([raw file](https://github.com/netsec-ethz/scionlab/blob/82235c720d0783645e1312f9f720c9dc034c5fa7/scionlab/hostfiles/scionlab-config#L82)):*
> ```
> logging.basicConfig(format='%(levelname)s: %(message)s', level=logging.WARNING)
> ```

Nit: keep two blank lines here and please remove the trailing whitespace below. The linter will complain (run `flake8`, see the README). 
___
*[scionlab/hostfiles/scionlab-config, line 99 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLCsWi41YDvHgxACCGa:-MLCsWi41YDvHgxACCGb:bf779fw) ([raw file](https://github.com/netsec-ethz/scionlab/blob/82235c720d0783645e1312f9f720c9dc034c5fa7/scionlab/hostfiles/scionlab-config#L99)):*
> ```
>         else:
>             install_config(args, config)
>             confirm_deployed(args)
> ```

Why are we removing this? Tracking this is now clearly less important without the config pushing, but I think we should keep it anyway (at least for now). Luckily, it looks like you haven't removed the `config_version_deployed` on the server side.
___
*[scionlab/hostfiles/scionlab-config, line 102 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLCtvJW3CNcyGB8p4Fy:-MLCtvJW3CNcyGB8p4Fz:b-gibbmh) ([raw file](https://github.com/netsec-ethz/scionlab/blob/82235c720d0783645e1312f9f720c9dc034c5fa7/scionlab/hostfiles/scionlab-config#L102)):*
> ```
>     else:
>         tar = tarfile.open(args.tar, mode='r')
>         install_config(args, tar)
> ```

Bad merge?
___
*[scionlab/hostfiles/scionlab-config@.service, line 12 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLCu8fl5rzT69_NOVze:-MLCu8fm5mgZWq7AZ_JO:b-dm405a) ([raw file](https://github.com/netsec-ethz/scionlab/blob/ec947461c953f265b9bf4007d0eeb7426be9f535/scionlab/hostfiles/scionlab-config@.service#L12)):*
> ```
> ExecStartPre=/usr/bin/bash -c "/usr/bin/systemctl set-environment HOST_SECRET=$${INPUT#*:}"
> #running the script
> ExecStart=/usr/bin/bash -c "exec scionlab-config --host-id $HOST_ID --host-secret $HOST_SECRET --daemon"
> ```

Unless there is a good reason to use environment variables for the host id/secrets, this seems unnecessarily complicated; here's a single bash line:
```
ExecStart=/usr/bin/bash -c 'instance_name="%I"; exec scionlab-config --host-id "$${instance_name%:$}" --host-secret "$${instance_name#*:}" --daemon'
```
___
*[scionlab/migrations/0001_initial.py, line 96 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLCvOgdEKbqg2CSr7Tn:-MLCvOgdEKbqg2CSr7To:bm80ez2) ([raw file](https://github.com/netsec-ethz/scionlab/blob/82235c720d0783645e1312f9f720c9dc034c5fa7/scionlab/migrations/0001_initial.py#L96)):*
> ```Python
>                 ('bind_ip', models.GenericIPAddressField(blank=True, help_text='Default bind IP for for border router interfaces running on this host.', null=True)),
>                 ('label', models.CharField(blank=True, max_length=255, null=True)),
>                 ('managed', models.BooleanField(default=False)),
> ```

Nonono, do not touch the old migration files please.
Just leave this as it is, then run `makemigrations` (like you seem to have done for adding the `updated_at` field). This will then create a migration to properly _remove_ the field.
___
*[scionlab/migrations/0007_auto_20201007_0515.py, line 28 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLCvrhmDKy_cinNJRHG:-MLCvrhmDKy_cinNJRHH:bfzm6mu) ([raw file](https://github.com/netsec-ethz/scionlab/blob/ec947461c953f265b9bf4007d0eeb7426be9f535/scionlab/migrations/0007_auto_20201007_0515.py#L28)):*
> ```Python
>             name='trc',
>             field=jsonfield.fields.JSONField(editable=False),
>         ),
> ```

What happened with the `trc` and `certificate` fields? These shouldn't be here, I think.
And, as commented above, this migration file should include a `RemoveField` (or whatever it's called) to remove the `managed` field.
___
*[scionlab/models/user_as.py, line 438 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLCw_KB4sj5EBTVfNps:-MLCw_KB4sj5EBTVfNpt:bscpor4) ([raw file](https://github.com/netsec-ethz/scionlab/blob/ec947461c953f265b9bf4007d0eeb7426be9f535/scionlab/models/user_as.py#L438)):*
> ```Python
>     def active(self):
>         threshold = timezone.now() - datetime.timedelta(minutes=1)
>         return self.filter(updated_at__gt = threshold)
> ```

As commented on the related change to use this function, I'd prefer to move this change to the separate PR for the User AP feature.
Btw thou [...]

2020-11-03 16:44 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/313)* status: all files reviewed, 15 unresolved discussions (waiting on @fl99kl)

___
*[scionlab/models/user_as.py, line 438 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLCw_KB4sj5EBTVfNps:-MLDzBym6_zJ6ZtkVNSz:b-23kmg4) ([raw file](https://github.com/netsec-ethz/scionlab/blob/ec947461c953f265b9bf4007d0eeb7426be9f535/scionlab/models/user_as.py#L438)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

As commented on the related change to use this function, I'd prefer to move this change to the separate PR for the User AP feature.
Btw though, for when you add it in the other PR:
- please move this constant 1 minute threshold to the settings
- timezones are not enabled and we've usually used UTC time (search for `utcnow`). This stuff seems overly complicated/messy in django unfortunately
- please ensure that infrastructure APs are never filtered from the UI
- there appear to be two 
Not sure about the `updated_at` field itself -- ok for me to leave this in this PR to avoid further DB changes.
</blockquote></details>

Sorry, I didn't quite finish writing this before publishing; please just ignore the garbled half sentence at the beginning of the last bullet point.


<!-- Sent from Reviewable.io -->

2020-11-05 08:15 UTC, matzf reviewed
> Reviewed 12 of 15 files at r3, 1 of 1 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/313)* status: all files reviewed, 11 unresolved discussions (waiting on @fl99kl)

___
*[docker-compose.yml, line 17 at r5](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLMKkpEARuFNR54mvJ9:-MLMKkpEARuFNR54mvJA:b-1xpaew) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e0aa21a957bd9cba1417dcfa5dc03351e014b14d/docker-compose.yml#L17)):*
> ```YAML
>       - "8000"
>     depends_on:
>       - redis
> ```

Aha, we can drop redis too (was used only by huey).
___
*[.circleci/config.yml, line 66 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLCqg9465J1b6qOL0-E:-MLMP8cY1efYOxJJ85G5:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/ec947461c953f265b9bf4007d0eeb7426be9f535/.circleci/config.yml#L66)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Everything after `init-test-db.sh` should be removed here.
</blockquote></details>

Done.
___
*[.circleci/config.yml, line 195 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLD7IgF0LlI1SQjeQ81:-MLMSpFi5D187lyxWBWI:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/82235c720d0783645e1312f9f720c9dc034c5fa7/.circleci/config.yml#L195)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Would be nice to keep this test and just change it to "Pull" instead.
</blockquote></details>

Done.
___
*[.circleci/config.yml, line 207 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLD6ehv-902ncIfxYoA:-MLMPi7m8O9PAf_PdQqM:b-2gf6u3) ([raw file](https://github.com/netsec-ethz/scionlab/blob/ec947461c953f265b9bf4007d0eeb7426be9f535/.circleci/config.yml#L207)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

More push deploy here.
Needs to be changed to a `pull`, something along the lines of `docker-compose exec -T as1301 scionlab-config`.
</blockquote></details>

Almost done; simplify invocation to `docker-compose exec -T $c scionlab-config -- parameters don't need to be passed again (same comment as above).
___
*[.circleci/config.yml, line 209 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLCr1_p3Vi_yWC8DC9v:-MLMPjLeCzrzsliKDHjd:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/ec947461c953f265b9bf4007d0eeb7426be9f535/.circleci/config.yml#L209)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

> ```
> huey
> ```
This is gone.
Btw, remove `huey` from `.circleci/docker-compose.yml` and `docker-compose.yml`.
</blockquote></details>

Done.
___
*[.circleci/config.yml, line 204 at r5](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLMPNKF7XpOUBWhxHm3:-MLMPNKF7XpOUBWhxHm4:b-q3m2b) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e0aa21a957bd9cba1417dcfa5dc03351e014b14d/.circleci/config.yml#L204)):*
> ```YAML
>             'python .circleci/actions/update-keys.py ffaa:0:1303'
>             docker-compose exec as1303 /bin/bash -c \
>               'scionlab-config --host-id ${SCIONLAB_HOST_ID} --host-secret ${SCIONLAB_HOST_SECRET} --url http://coord:8000'
> ```

Simplify to `docker-compose exec 1303 scionlab-config` -- no need to pass the host-id/secret and url again as these are stored in the containers config file after the first run.
___
*[scionlab/forms/attachment_conf_form.py, line 312 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLCrgdR0RppHZsPRmmI:-MLMQ6AVDBCWdZngKR3_:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/ec947461c953f265b9bf4007d0eeb7426be9f535/scionlab/forms/attachment_conf_form.py#L312)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Lets leave this change (and the related change above in the same file) for the separate PR with the user AP feature, ok?
</blockquote></details>

Done.
___
*[scionlab/forms/user_as_form.py, line 144 at r5](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLMQ9fc6F_w8r6L5Prb:-MLMQ9fc6F_w8r6L5Prc:b5zkmnm) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e0aa21a957bd9cba1417dcfa5dc03351e014b14d/scionlab/forms/user_as_form.py#L144)):*
> ```Python
>             )
>             host = user_as.hosts.first()
>             host.update_timestamp()
> ```

Any particular reason for this? The original for this timestamp seemed to be to record the time when the configuration was fetched, in order to keep track of "liveness". Here, you record the time of a change to the configuration. Unless I'm missing something, this change here is not necessary.
___
*[scionlab/hostfiles/scionlab-config, line 82 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLCsJRd6jnxry-IY7nd:-MLMOEMH5iAATRZz9W5W:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/82235c720d0783645e1312f9f720c9dc034c5fa7/scionlab/hostfiles/scionlab-config#L82)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit: keep two blank lines here and please remove the trailing whitespace below. The linter will complain (run `flake8`, see the README). 
</blockquote></details>

Done.
___
*[scionlab/hostfiles/scionlab-config, line 99 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLCsWi41YDvHgxACCGa:-MLMODib4Ueorii9zIZh:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/82235c720d0783645e1312f9f720c9dc034c5fa7/scionlab/hostfiles/scionlab-config#L99)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Why are we removing this? Tracking this is now clearly less important without the config pushing, but I think we should keep it anyway (at least for now). Luckily, it looks like you haven't removed the `config_version_deployed` on the server side.
</blockquote></details>

Done.
___
*[scionlab/hostfiles/scionlab-config, line 102 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLCtvJW3CNcyGB8p4Fy:-MLMOCVj6AajecuChOs-:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/82235c720d0783645e1312f9f720c9dc034c5fa7/scionlab/hostfiles/scionlab-config#L102)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Bad merge?
</blockquote></details>

Done.
___
*[scionlab/hostfiles/scionlab-config, line 103 at r5](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLMNeLI0UokH8InEbxx:-MLMNeLJ-uRDiwb4aH0k:bkhswum) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e0aa21a957bd9cba1417dcfa5dc03351e014b14d/scionlab/hostfiles/scionlab-config#L103)):*
> ```
>             if not args.daemon:
>                 break
>             time.sleep(20)
> ```

Let's go with 10 seconds for now. Please make this a named constant (e.g. `DAEMON_REQUEST_INTERVAL_SECONDS`).
___
*[scionlab/hostfiles/scionlab-config@.service, line 12 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLCu8fl5rzT69_NOVze:-MLMO66X83xI8eUaXMhm:bq16np5) ([raw file](https://github.com/netsec-ethz/scionlab/blob/ec947461c953f265b9bf4007d0eeb7426be9f535/scionlab/hostfiles/scionlab-config@.service#L12)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Unless there is a good reason to use environment variables for the host id/secrets, this seems unnecessarily complicated; here's a single bash line:
```
ExecStart=/usr/bin/bash -c 'instance_name="%I"; exec scionlab-config --host-id "$${instance_name%:$}" --host-secret "$${instance_name#*:}" --daemon'
```
</blockquote></details>

Almost done; looks like you copied my typo here, the host id should probably be `"$${instance_name%:*}"`.
___
*[scionlab/migrations/0001_initial.py, line 96 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLCvOgdEKbqg2CSr7Tn:-MLMO3MH2ucmvGGjNelN:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/82235c720d0783645e1312f9 [...]

2020-11-05 19:34 UTC, fl99kl reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/313)* status: 9 of 18 files reviewed, 11 unresolved discussions (waiting on @matzf)

___
*[docker-compose.yml, line 17 at r5](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLMKkpEARuFNR54mvJ9:-MLOt5uT-nfEhjQD-oSh:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e0aa21a957bd9cba1417dcfa5dc03351e014b14d/docker-compose.yml#L17)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Aha, we can drop redis too (was used only by huey).
</blockquote></details>

Done.
___
*[.circleci/config.yml, line 207 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLD6ehv-902ncIfxYoA:-MLOt8bB6-_7oqn65ZKy:b-quidqz) ([raw file](https://github.com/netsec-ethz/scionlab/blob/ec947461c953f265b9bf4007d0eeb7426be9f535/.circleci/config.yml#L207)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Almost done; simplify invocation to `docker-compose exec -T $c scionlab-config -- parameters don't need to be passed again (same comment as above).
</blockquote></details>

Done, if it refers to the same as the comment above
___
*[.circleci/config.yml, line 204 at r5](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLMPNKF7XpOUBWhxHm3:-MLOt6s9CZqEG8k9gKHq:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e0aa21a957bd9cba1417dcfa5dc03351e014b14d/.circleci/config.yml#L204)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Simplify to `docker-compose exec 1303 scionlab-config` -- no need to pass the host-id/secret and url again as these are stored in the containers config file after the first run.
</blockquote></details>

Done.
___
*[.circleci/Dockerfile-scionHost, line 30 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLD7Vb27AiLqHP3jsRK:-MLOtTtOCMRl92t_buSg:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/ec947461c953f265b9bf4007d0eeb7426be9f535/.circleci/Dockerfile-scionHost#L30)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Remove left over comment ("& configure authorized_keys ...")
</blockquote></details>

Done.
___
*[scionlab/forms/user_as_form.py, line 144 at r5](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLMQ9fc6F_w8r6L5Prb:-MLOtYS87VYVgoB-n0ti:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e0aa21a957bd9cba1417dcfa5dc03351e014b14d/scionlab/forms/user_as_form.py#L144)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Any particular reason for this? The original for this timestamp seemed to be to record the time when the configuration was fetched, in order to keep track of "liveness". Here, you record the time of a change to the configuration. Unless I'm missing something, this change here is not necessary.
</blockquote></details>

Done.
___
*[scionlab/hostfiles/scionlab-config, line 103 at r5](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLMNeLI0UokH8InEbxx:-MLOtZW_-NrXZEQULARF:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e0aa21a957bd9cba1417dcfa5dc03351e014b14d/scionlab/hostfiles/scionlab-config#L103)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Let's go with 10 seconds for now. Please make this a named constant (e.g. `DAEMON_REQUEST_INTERVAL_SECONDS`).
</blockquote></details>

Done.
___
*[scionlab/hostfiles/scionlab-config@.service, line 12 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLCu8fl5rzT69_NOVze:-MLOt_oL48E6Aa3UFknt:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/ec947461c953f265b9bf4007d0eeb7426be9f535/scionlab/hostfiles/scionlab-config@.service#L12)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Almost done; looks like you copied my typo here, the host id should probably be `"$${instance_name%:*}"`.
</blockquote></details>

Done.
___
*[scionlab/models/core.py, line 607 at r5](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLMQyR26ZAQTKTuV2Bv:-MLOsSPP4u6yy94PRzdC:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e0aa21a957bd9cba1417dcfa5dc03351e014b14d/scionlab/models/core.py#L607)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Can you maybe think of a name for the `updated_at` timestamp that describes the use a bit better? "Updated" is really quite ambiguous here. Perhaps `config_queried_at`?  Analogously for this `update_timestamp` function, maybe `update_config_queried_timestamp`?
</blockquote></details>

Done.
___
*[scionlab/models/core.py, line 607 at r5](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLMSY8x50aozgp-FZRP:-MLOsWIP-QfkD8sHO8Fo:bz6piqd) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e0aa21a957bd9cba1417dcfa5dc03351e014b14d/scionlab/models/core.py#L607)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

As in a previous comment at a different location; timezones are not enabled and we've usually used UTC time (search for utcnow). This stuff seems overly complicated/messy in django unfortunately.
</blockquote></details>

I set TIME_ZONE to UTC in the Settings. This also seems to solve it.
___
*[scionlab/views/api.py, line 74 at r5](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLMOfVr8kMdCY6mU7CF:-MLOt4Iz0HksL_ze6xeG:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e0aa21a957bd9cba1417dcfa5dc03351e014b14d/scionlab/views/api.py#L74)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Just update the timestamp, no check for existing AP.
</blockquote></details>

Done.
___
*[scionlab/migrations/0007_auto_20201103_1151.py, line 1 at r5](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLMT5Ev7xKXzNOLwMkN:-MLOsJBIAhXnNqQPxSmw:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e0aa21a957bd9cba1417dcfa5dc03351e014b14d/scionlab/migrations/0007_auto_20201103_1151.py#L1)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Could you rename this to e.g. `007_pullap.py`, please?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-18 21:29 UTC, matzf reviewed
> Reviewed 7 of 10 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/313)* status: 17 of 19 files reviewed, 3 unresolved discussions (waiting on @fl99kl and @matzf)

___
*[scionlab/models/core.py, line 607 at r5](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLMSY8x50aozgp-FZRP:-MMSCupa44u0vbXceVZU:b-t7e6qz) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e0aa21a957bd9cba1417dcfa5dc03351e014b14d/scionlab/models/core.py#L607)):*
<details><summary><i>Previously, fl99kl wrote…</i></summary><blockquote>

I set TIME_ZONE to UTC in the Settings. This also seems to solve it.
</blockquote></details>

Please don't, please use `utcnow`. There are "naive" (as returned by `utcnow`) and "aware" (as returned by `timezone.now()`) datetime objects and that's not something we want to mix.
___
*[scionlab/models/core.py, line 607 at r5](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLMQyR26ZAQTKTuV2Bv:-MMSFW3E57VTPk1apC42:bm0izm3) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e0aa21a957bd9cba1417dcfa5dc03351e014b14d/scionlab/models/core.py#L607)):*
<details><summary><i>Previously, fl99kl wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you please change the name of the method, too? Maybe `update_config_queried_timestamp`.


<!-- Sent from Reviewable.io -->

2020-11-19 16:40 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/313)* status: 17 of 19 files reviewed, 5 unresolved discussions (waiting on @fl99kl and @matzf)

___
*[scionlab/admin.py, line 196 at r8](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MMWMcJXDEsYcPZms83w:-MMWMcJY9WprpHxc_q-1:b-832rwa) ([raw file](https://github.com/netsec-ethz/scionlab/blob/dc04b44a5202065a2b1ef1c0798be451eb99935b/scionlab/admin.py#L196)):*
> ```Python
> class HostAdminForm(_CreateUpdateModelForm):
>     class Meta:
>         fields = ('AS', 'internal_ip', 'public_ip', 'bind_ip', 'label', 'ssh_host', 'config_queried_at')
> ```

The `config_queried_at` field does not have to be modifiable by the admin. Remove this here (or put it to `readonly_fields`).
___
*[scionlab/admin.py, line 209 at r8](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MMWMz22C3XWWMQ1XBpq:-MMWMz238Pu9PLqU9pe_:b-8qgez4) ([raw file](https://github.com/netsec-ethz/scionlab/blob/dc04b44a5202065a2b1ef1c0798be451eb99935b/scionlab/admin.py#L209)):*
> ```Python
>             ssh_host=self.cleaned_data['ssh_host'],
>             secret=self.cleaned_data['secret'],
>             config_queried_at=self.cleaned_data['config_queried_at'],
> ```

See comment above; remove this here and remove this parameter in `Host.objects.create` / `update`.


<!-- Sent from Reviewable.io -->

2020-11-19 18:21 UTC, fl99kl reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/313)* status: 12 of 19 files reviewed, 5 unresolved discussions (waiting on @matzf)

___
*[scionlab/admin.py, line 196 at r8](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MMWMcJXDEsYcPZms83w:-MMWiEPf9c3mYafBCALj:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/dc04b44a5202065a2b1ef1c0798be451eb99935b/scionlab/admin.py#L196)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

The `config_queried_at` field does not have to be modifiable by the admin. Remove this here (or put it to `readonly_fields`).
</blockquote></details>

Done.
___
*[scionlab/admin.py, line 209 at r8](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MMWMz22C3XWWMQ1XBpq:-MMWiJEjBQwon9QoObww:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/dc04b44a5202065a2b1ef1c0798be451eb99935b/scionlab/admin.py#L209)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

See comment above; remove this here and remove this parameter in `Host.objects.create` / `update`.
</blockquote></details>

Done.
___
*[scionlab/models/core.py, line 607 at r5](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLMQyR26ZAQTKTuV2Bv:-MMWjK4N9v0KS9AQ1a9g:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e0aa21a957bd9cba1417dcfa5dc03351e014b14d/scionlab/models/core.py#L607)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Can you please change the name of the method, too? Maybe `update_config_queried_timestamp`.
</blockquote></details>

Done.
___
*[scionlab/models/core.py, line 607 at r5](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MLMSY8x50aozgp-FZRP:-MMWjPEqB-BnUzI6dxWa:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e0aa21a957bd9cba1417dcfa5dc03351e014b14d/scionlab/models/core.py#L607)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Please don't, please use `utcnow`. There are "naive" (as returned by `utcnow`) and "aware" (as returned by `timezone.now()`) datetime objects and that's not something we want to mix.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-17 09:20 UTC, matzf reviewed
> Reviewed 13 of 19 files at r12.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/313)* status: 13 of 19 files reviewed, 2 unresolved discussions (waiting on @fl99kl and @matzf)

___
*[scionlab/hostfiles/scionlab-config@.service, line 7 at r12](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MOjxFUs6b4eDEu_FIoj:-MOjxFUs6b4eDEu_FIok:b-vqk7jq) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e586a09c0ae2cef75baafeeb68650f40931a18ea/scionlab/hostfiles/scionlab-config@.service#L7)):*
> ```
> [Service]
> Type=simple
> ExecStart=/usr/bin/bash -c 'instance_name="%I"; exec scionlab-config --host-id "$${instance_name%:*}" --host-secret "$${instance_name#*:}" --daemon'
> ```

Looking at this again now, this approach with having the host id and secret in the unit's instance name feels rather awkward. As an alternative we could simply run `scionlab-config --daemon` here. We can assume that the host-id and secret are already configured in `/etc/scion/scionlab-config.json` -- if this is not the case, the unit will simply fail.

The workflow to set up an attachment point (or any host with automatic config fetching), we would then need to:
1. run `scionlab-config --host-id ... --host-secret [--url=...]`
2. start/enable the daemon unit: `systemctl enable --now scionlab-config.service`

We could optionally replace the first step by simply writing the host id/secret to the scionlab-config.json file, if this is for any particular reason desirable -- this would have the disadvantage that e.g. a wrong id/secret would only be detected later.

Not blocking; it's ok to change this in a follow up.
___
*[scionlab/migrations/0007_pullap.py, line 10 at r12](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MOjzi3aDKEjJn_p_QZy:-MOjzi3aDKEjJn_p_QZz:behk9e6) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e586a09c0ae2cef75baafeeb68650f40931a18ea/scionlab/migrations/0007_pullap.py#L10)):*
> ```Python
> 
>     dependencies = [
>         ('scionlab', '0006_pki'),
> ```

This migration needs to be "rebased" on the current latest migration (other migrations have been created in the meantime). Simplest approach might be to just delete it and recreate.


<!-- Sent from Reviewable.io -->

2021-01-04 17:13 UTC, fl99kl reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/313)* status: 0 of 19 files reviewed, 2 unresolved discussions (waiting on @matzf)

___
*[scionlab/hostfiles/scionlab-config@.service, line 7 at r12](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MOjxFUs6b4eDEu_FIoj:-MQDNoEp8sYrpwaCatT0:b-rvvkz0) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e586a09c0ae2cef75baafeeb68650f40931a18ea/scionlab/hostfiles/scionlab-config@.service#L7)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Looking at this again now, this approach with having the host id and secret in the unit's instance name feels rather awkward. As an alternative we could simply run `scionlab-config --daemon` here. We can assume that the host-id and secret are already configured in `/etc/scion/scionlab-config.json` -- if this is not the case, the unit will simply fail.

The workflow to set up an attachment point (or any host with automatic config fetching), we would then need to:
1. run `scionlab-config --host-id ... --host-secret [--url=...]`
2. start/enable the daemon unit: `systemctl enable --now scionlab-config.service`

We could optionally replace the first step by simply writing the host id/secret to the scionlab-config.json file, if this is for any particular reason desirable -- this would have the disadvantage that e.g. a wrong id/secret would only be detected later.

Not blocking; it's ok to change this in a follow up.
</blockquote></details>

changed it already
___
*[scionlab/migrations/0007_pullap.py, line 10 at r12](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MOjzi3aDKEjJn_p_QZy:-MQDN0O0D_yr8njrYWzQ:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e586a09c0ae2cef75baafeeb68650f40931a18ea/scionlab/migrations/0007_pullap.py#L10)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This migration needs to be "rebased" on the current latest migration (other migrations have been created in the meantime). Simplest approach might be to just delete it and recreate.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-05 10:46 UTC, matzf requested changes
> Reviewed 19 of 19 files at r15.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/313)* status: all files reviewed, 4 unresolved discussions (waiting on @fl99kl)

___
*[.circleci/config.yml, line 233 at r15](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MQH3Eg9A-wrm7iaKAA-:-MQH3EgAD43dGKtxf73Y:bdgo3yn) ([raw file](https://github.com/netsec-ethz/scionlab/blob/3fbcb152eea952c84bec3232bf3124a5e2525a3f/.circleci/config.yml#L233)):*
> ```YAML
>             for c in as1301 as1303 as1305; do
>               docker-compose exec $c /bin/bash -c \
>                 'scionlab-config --host-id ${SCIONLAB_HOST_ID} --host-secret ${SCIONLAB_HOST_SECRET} --url http://coord:8000'
> ```

Nit: credentials already set; just `docker compose exec -T $c scionlab-config`, as above.
___
*[scionlab/models/core.py, line 477 at r15](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MQH5vc4B4WyODouN7JH:-MQH5vc4B4WyODouN7JI:b7bdgku) ([raw file](https://github.com/netsec-ethz/scionlab/blob/3fbcb152eea952c84bec3232bf3124a5e2525a3f/scionlab/models/core.py#L477)):*
> ```Python
>                ssh_host=_placeholder,
>                secret=_placeholder,
>                config_queried_at=_placeholder):
> ```

Updating `config_queried_at` doesn't seem to belong here, and you've already passing the parameter from in the only place that calls this function. Drop this here, too.
___
*[scionlab/hostfiles/scionlab-config.service, line 2 at r15](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MQH4MaM8Lu8YYnl7Fep:-MQH4MaM8Lu8YYnl7Feq:b-h2j6qe) ([raw file](https://github.com/netsec-ethz/scionlab/blob/3fbcb152eea952c84bec3232bf3124a5e2525a3f/scionlab/hostfiles/scionlab-config.service#L2)):*
> ```
> [Unit]
> Description=service to start scionlab-config script in daemon mode
> ```

Nit: description could be better (see https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Description=), e.g.
```
Description=SCIONLab node configuration daemon
```
___
*[scionlab/hostfiles/scionlab-config@.service, line 7 at r12](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MOjxFUs6b4eDEu_FIoj:-MQH5K1a6PjI4crzHCUw:b-g5chq5) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e586a09c0ae2cef75baafeeb68650f40931a18ea/scionlab/hostfiles/scionlab-config@.service#L7)):*
<details><summary><i>Previously, fl99kl wrote…</i></summary><blockquote>

changed it already
</blockquote></details>

Excellent!

One nit: now you no longer need a shell in `ExecStart` and just make it:
```
ExecStart=scionlab-config --daemon
```


<!-- Sent from Reviewable.io -->

2021-01-06 14:42 UTC, cmeury requested changes
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/313)* status: all files reviewed, 8 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[docker-compose.yml, line 9 at r15](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MQN4WXk7xKQ2a4RCgYU:-MQN4WXk7xKQ2a4RCgYV:be30mn8) ([raw file](https://github.com/netsec-ethz/scionlab/blob/ac2ba1f6c5a17c508a5e20d1a9dcee716d1b3547/docker-compose.yml#L9)):*
> ```YAML
>       - redisdata:/data:Z
> 
>   huey:
> ```

Huey is still present in some other places:
- `requirements.txt`
- `scionlab/settings/development.py`
- `scionlab/settings/common.py`
- `scionlab/settings/production.py`
- `README.md`
- `requirements.in`
___
*[scionlab/models/core.py, line 487 at r15](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MQN4sTF-IocvtYc3Kda:-MQN4sTF-IocvtYc3Kdb:b-ssv0lk) ([raw file](https://github.com/netsec-ethz/scionlab/blob/3fbcb152eea952c84bec3232bf3124a5e2525a3f/scionlab/models/core.py#L487)):*
> ```Python
>         :param str label: optional
>         :param str ssh_host: optional, hostname/IP for management access via SSH
>         :param str secret: optional, a secret to authenticate the host. If `None` is given, a new
> ```

Missing `config_queried_at` in documentation.
___
*[scionlab/models/core.py, line 546 at r15](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MQN50fkAzSS9EUE3n3e:-MQN50fkAzSS9EUE3n3f:b8z5h9s) ([raw file](https://github.com/netsec-ethz/scionlab/blob/3fbcb152eea952c84bec3232bf3124a5e2525a3f/scionlab/models/core.py#L546)):*
> ```Python
>         """
>         Find an unused public port for an AS interface on this Host
>         """        
> ```

Accidental whitespace added.
___
*[scionlab/hostfiles/scionlab-config.service, line 5 at r15](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MQMzGFO0U8_1xdWYzH7:-MQMzGFO0U8_1xdWYzH8:bn7lfxm) ([raw file](https://github.com/netsec-ethz/scionlab/blob/3fbcb152eea952c84bec3232bf3124a5e2525a3f/scionlab/hostfiles/scionlab-config.service#L5)):*
> ```
> #this expects the host-id and host-secret to already be present in /etc/scion/scionlab-config.json
> 
> [Service]
> ```

Doesn't this service need a 

```
[Install]
WantedBy=multi-user.target
```

So it's not started before we have networking?
___
*[scionlab/hostfiles/scionlab-config@.service, line 7 at r12](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MOjxFUs6b4eDEu_FIoj:-MQN1XHo5BNI1EXXdbR9:b-2m4ttf) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e586a09c0ae2cef75baafeeb68650f40931a18ea/scionlab/hostfiles/scionlab-config@.service#L7)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Excellent!

One nit: now you no longer need a shell in `ExecStart` and just make it:
```
ExecStart=scionlab-config --daemon
```
</blockquote></details>

How do we provision `/etc/scion/scionlab-config.json` in the first place? Say, when we add a new node? Just manually create it?


<!-- Sent from Reviewable.io -->

2021-01-06 15:30 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/313)* status: all files reviewed, 8 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[scionlab/hostfiles/scionlab-config@.service, line 7 at r12](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MOjxFUs6b4eDEu_FIoj:-MQNJLdP2H_g_f_bpCj2:bi7jxr1) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e586a09c0ae2cef75baafeeb68650f40931a18ea/scionlab/hostfiles/scionlab-config@.service#L7)):*
<details><summary><i>Previously, cmeury (Cedric Meury) wrote…</i></summary><blockquote>

How do we provision `/etc/scion/scionlab-config.json` in the first place? Say, when we add a new node? Just manually create it?
</blockquote></details>

Yes, either manually create the json file or simpler by running `scionlab-config --host-id ... --host-secret ...`.


<!-- Sent from Reviewable.io -->

2021-01-07 18:54 UTC, fl99kl reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/313)* status: 15 of 24 files reviewed, 6 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[docker-compose.yml, line 9 at r15](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MQN4WXk7xKQ2a4RCgYU:-MQTBLaH24Y1OcXfAObJ:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/ac2ba1f6c5a17c508a5e20d1a9dcee716d1b3547/docker-compose.yml#L9)):*
<details><summary><i>Previously, cmeury (Cedric Meury) wrote…</i></summary><blockquote>

Huey is still present in some other places:
- `requirements.txt`
- `scionlab/settings/development.py`
- `scionlab/settings/common.py`
- `scionlab/settings/production.py`
- `README.md`
- `requirements.in`
</blockquote></details>

Done.
___
*[.circleci/config.yml, line 233 at r15](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MQH3Eg9A-wrm7iaKAA-:-MQT9wraEC96jIwD7iDz:b-f63qo2) ([raw file](https://github.com/netsec-ethz/scionlab/blob/3fbcb152eea952c84bec3232bf3124a5e2525a3f/.circleci/config.yml#L233)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit: credentials already set; just `docker compose exec -T $c scionlab-config`, as above.
</blockquote></details>

Does the url has to be specified here? (here and above)
___
*[scionlab/models/core.py, line 477 at r15](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MQH5vc4B4WyODouN7JH:-MQTB2qN6ZIQ7I6pjVd-:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/3fbcb152eea952c84bec3232bf3124a5e2525a3f/scionlab/models/core.py#L477)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Updating `config_queried_at` doesn't seem to belong here, and you've already passing the parameter from in the only place that calls this function. Drop this here, too.
</blockquote></details>

Done.
___
*[scionlab/models/core.py, line 487 at r15](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MQN4sTF-IocvtYc3Kda:-MQTB3t4BzIaEhN3PoEX:b-78la93) ([raw file](https://github.com/netsec-ethz/scionlab/blob/3fbcb152eea952c84bec3232bf3124a5e2525a3f/scionlab/models/core.py#L487)):*
<details><summary><i>Previously, cmeury (Cedric Meury) wrote…</i></summary><blockquote>

Missing `config_queried_at` in documentation.
</blockquote></details>

removed config_queried_at from here
___
*[scionlab/models/core.py, line 546 at r15](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MQN50fkAzSS9EUE3n3e:-MQTB9TB17wnBWcBeyyA:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/3fbcb152eea952c84bec3232bf3124a5e2525a3f/scionlab/models/core.py#L546)):*
<details><summary><i>Previously, cmeury (Cedric Meury) wrote…</i></summary><blockquote>

Accidental whitespace added.
</blockquote></details>

Done.
___
*[scionlab/hostfiles/scionlab-config.service, line 2 at r15](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MQH4MaM8Lu8YYnl7Fep:-MQTAlYV3nhR4f1quGIm:bb6un1j) ([raw file](https://github.com/netsec-ethz/scionlab/blob/3fbcb152eea952c84bec3232bf3124a5e2525a3f/scionlab/hostfiles/scionlab-config.service#L2)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit: description could be better (see https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Description=), e.g.
```
Description=SCIONLab node configuration daemon
```
</blockquote></details>

Done
___
*[scionlab/hostfiles/scionlab-config.service, line 5 at r15](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MQMzGFO0U8_1xdWYzH7:-MQTAn_-4GCFR1KuJbcj:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/3fbcb152eea952c84bec3232bf3124a5e2525a3f/scionlab/hostfiles/scionlab-config.service#L5)):*
<details><summary><i>Previously, cmeury (Cedric Meury) wrote…</i></summary><blockquote>

Doesn't this service need a 

```
[Install]
WantedBy=multi-user.target
```

So it's not started before we have networking?
</blockquote></details>

Done.
___
*[scionlab/hostfiles/scionlab-config@.service, line 7 at r12](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MOjxFUs6b4eDEu_FIoj:-MQTBPIc4rB7hXZIyj-J:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/e586a09c0ae2cef75baafeeb68650f40931a18ea/scionlab/hostfiles/scionlab-config@.service#L7)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Yes, either manually create the json file or simpler by running `scionlab-config --host-id ... --host-secret ...`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-08 09:25 UTC, matzf approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 8 of 9 files at r16, 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-:-MQWJC1x940M78kwTa9i:b-uwkowd)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[requirements.in, line 14 at r17](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MQWIHBoBj3D8dr8p3ld:-MQWIHBoBj3D8dr8p3le:bxpk8c7) ([raw file](https://github.com/netsec-ethz/scionlab/blob/a4a0e55cb98ce284339d96e61ecfee19196171a8/requirements.in#L14)):*
> ```
> pynacl
> pyyaml>=4.2b1  # for fixtures and config generation; high severity vulnerability before 4.1 (CVE-2017-18342)
> redis
> ```

Nit: this can go, too and there is a left-over volume `redisdata` in `docker-compose.yml`.
___
*[.circleci/config.yml, line 233 at r15](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MQH3Eg9A-wrm7iaKAA-:-MQWHdQ1-pE5c2FLi4bK:b-dicjuk) ([raw file](https://github.com/netsec-ethz/scionlab/blob/3fbcb152eea952c84bec3232bf3124a5e2525a3f/.circleci/config.yml#L233)):*
<details><summary><i>Previously, fl99kl wrote…</i></summary><blockquote>

Does the url has to be specified here? (here and above)
</blockquote></details>

Nope, it's stored in `/etc/scion/scionlab-config.json` together with the host ID, secret and configuration version information. All good :+1: 


<!-- Sent from Reviewable.io -->

2021-01-11 09:37 UTC, cmeury approved these changes
> Reviewed 15 of 19 files at r15, 8 of 9 files at r16, 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/313)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[requirements.in, line 14 at r17](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MQWIHBoBj3D8dr8p3ld:-MQkmsWu7xLJQVdFR7Ai:b609nrf) ([raw file](https://github.com/netsec-ethz/scionlab/blob/a4a0e55cb98ce284339d96e61ecfee19196171a8/requirements.in#L14)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit: this can go, too and there is a left-over volume `redisdata` in `docker-compose.yml`.
</blockquote></details>

Makes sense to remove this as well.


<!-- Sent from Reviewable.io -->

2021-01-11 09:40 UTC, cmeury commented
Looks like this is moving forward; you can run flake8 locally to verify it's happy and there's a DB test that fails.

2021-01-12 11:08 UTC, fl99kl reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/313)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[requirements.in, line 14 at r17](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-MQWIHBoBj3D8dr8p3ld:-MQq8Vpg3D6ThGU2H-Gm:b-w64djy) ([raw file](https://github.com/netsec-ethz/scionlab/blob/a4a0e55cb98ce284339d96e61ecfee19196171a8/requirements.in#L14)):*
<details><summary><i>Previously, cmeury (Cedric Meury) wrote…</i></summary><blockquote>

Makes sense to remove this as well.
</blockquote></details>

removed redis from requirements.txt aswell


<!-- Sent from Reviewable.io -->

2021-01-12 12:51 UTC, matzf approved these changes
> Reviewed 6 of 6 files at r18.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/313)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-12 13:07 UTC, matzf approved these changes
The `prod` test setup is unfortunately failing now. It appears that removing the redis dependency made the django startup just a bit faster, so it is quicker than the DB startup. As it now needs to wait for the DB in 5s increments, the total startup became slower. This makes the hard coded `sleep 5` for the migrations to complete too short -- that was obviously not very robust.

Florian, could you please replace the `sleep 5` in `.circleci/config.yml:478` ("Load data from fixture to check (test) DB setup" step), by explicitly waiting for the webserver to come up (which is sufficient to know that the migrations are complete):
```sh
 docker-compose exec -T django appdeps.py --wait-secs 60 --port-wait django:8000
```

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-:-MQqfSha1HaqNQUqN80S:b8tdrdb)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-12 14:43 UTC, fl99kl reviewed
Done.

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/313#-:-MQr28yl9v-pUjhtmvI3:b-896fix)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2021-01-12 15:31 UTC, merged