New CP PKI
netsec-ethz/scionlab pull request #329
Opened 2020-11-21 23:04 UTC by juagargi

Pending:
- [ ] generate crypto material.
- [ ] modify models.
- [ ] fix tests.
- [ ] update to newer `cryptography` library (from `develop` branch).
- [ ] (after the `cryptography` update) change `sign_payload` to not use `scion-pki` but the `cryptography` library.
- [ ] migration: generate appropriate crypto material.
- [ ] fixture still mutates on every generation. TRC generation needs to be intercepted.
- [ ] simplify core models' calls to crypto.
- [ ] test we can still generate a TRC even after deleting all cores / creating them again.
- [ ] cleanup commented out / dead code.

2020-11-26 09:55 UTC, matzf reviewed
> Reviewed 2 of 57 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/329)* status: 2 of 57 files reviewed, 6 unresolved discussions (waiting on @juagargi)

___
*[scionlab/models/core.py, line 137 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MN2ao8R0UqENburThtl:-MN2ao8R0UqENburThtm:b-zi8x0) ([raw file](https://github.com/netsec-ethz/scionlab/blob/9f0d7330202d1950448516b57ee1cda93152d96a/scionlab/models/core.py#L137)):*
> ```Python
>             if is_core:
>                 isd.trcs.create()
> ```

This now misses certificate updates to all the other core ASes on the TRC bump, right? 
___
*[scionlab/models/trc.py, line 184 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MN2u2PEAsNV5jpfv8ZT:-MN2u2PEAsNV5jpfv8ZU:bddcmhu) ([raw file](https://github.com/netsec-ethz/scionlab/blob/9f0d7330202d1950448516b57ee1cda93152d96a/scionlab/models/trc.py#L184)):*
> ```Python
>     # See also can_update_regular
>     signatures = models.ManyToManyField(
>         Certificate,
> ```

Wouldn't it be more natural to make `signatures` a relation to `Key` here? It's the key that signs, not the certificate.  Perhaps the same applies to `votes`, but I'm not sure.
___
*[scionlab/models/trc.py, line 306 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MN2x_JjDoaeHO8n0ggr:-MN2x_JjDoaeHO8n0ggs:b-9p1err) ([raw file](https://github.com/netsec-ethz/scionlab/blob/9f0d7330202d1950448516b57ee1cda93152d96a/scionlab/models/trc.py#L306)):*
> ```Python
>         on_delete=models.CASCADE,
>     )
>     index = models.PositiveIntegerField()
> ```

I think we could do away with this custom through table. Ordering based on the `pk` should give use the same indices. And it would avoid the logic to set up these indices. What do you think?
___
*[scionlab/scion/trcs.py, line 149 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MN2lvov3x_BteCityOk:-MN2lvov3x_BteCityOl:bxfgf3s) ([raw file](https://github.com/netsec-ethz/scionlab/blob/9f0d7330202d1950448516b57ee1cda93152d96a/scionlab/scion/trcs.py#L149)):*
> ```Python
>             self._dump_certificates_to_files()
>             yield self
>         # only needed to allow nested call to configure():
> ```

Are there such nested calls? If so, why?
Anyway, I find this `configure` contextmanager and its use is a bit unnatural to read, to be honest. I would like to suggest to  implement a single entry point on `TRCConfig`:
```py
def generate(self: TRCConfig) -> bytes
  with TemporaryDirectory() as temp_dir:
    self.dump_certificates_to_files(temp_dir)   # preferrably, change this to _return_ the certificates (mutable state is hard to follow)
    self.gen_payload(temp_dir)
    signed_payload = ... 
    return conf.combine(temp_dir)
```

Or, even better, implement all these steps in a single entry point `generate()` on `TRCConfig`.
___
*[scionlab/scion/trcs.py, line 273 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MN2kOHUDC33hNJP76qZ:-MN2kOHUDC33hNJP76q_:bdjxi1i) ([raw file](https://github.com/netsec-ethz/scionlab/blob/9f0d7330202d1950448516b57ee1cda93152d96a/scionlab/scion/trcs.py#L273)):*
> ```Python
>         prev_cwd = os.getcwd()
>         try:
>             os.chdir(self._temp_dir)
> ```

Please don't `chdir` here, this could be executed concurrently. Instead, set `cwd=` in `subprocess.run`.
___
*[scionlab/scion/trcs.py, line 290 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MN2vUWC2vOUZm1YVUxy:-MN2vUWC2vOUZm1YVUxz:b-p90q69) ([raw file](https://github.com/netsec-ethz/scionlab/blob/9f0d7330202d1950448516b57ee1cda93152d96a/scionlab/scion/trcs.py#L290)):*
> ```Python
>     """ Return the utc datetime for a naive datetime """
>     assert dt.tzinfo is None, "Timestamps from DB are expected to be naive UTC datetimes"
>     return dt.replace(tzinfo=timezone.utc)
> ```

The purpose function seemed clearer before: return the `int` timestamp, working around the fact that `timestamp` on "naive" datetimes defaults to local time.
Just call this in `_get_conf` instead of directly using `timestamp`.


<!-- Sent from Reviewable.io -->

2020-11-26 13:33 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/329)* status: 1 of 58 files reviewed, 7 unresolved discussions (waiting on @juagargi and @matzf)

___
*[scionlab/scion/trcs.py, line 156 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MN3j3zNEkWyZdM00dB1:-MN3j3zOCKTmncQclDVu:bv50zsw) ([raw file](https://github.com/netsec-ethz/scionlab/blob/9f0d7330202d1950448516b57ee1cda93152d96a/scionlab/scion/trcs.py#L156)):*
> ```Python
>         conf = self._get_conf()
>         with open(self._tmp_join(self.CONFIG_FILENAME), "w") as f:
>             f.write(toml.dumps(conf))
> ```

Here and in many many other places: writing a file like this can be shortened by using `pathlib.Path(...).write_text(...)`. There is also `write_bytes`, `read_text` and `read_bytes`.
The `pathlib.Path` constructor is also a convenient shortcut to `os.path.join`, e.g. `pathlib.Path(tmp_dir, self.CONFIG_FILENAME)`.


<!-- Sent from Reviewable.io -->

2020-11-26 13:33 UTC, juagargi reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/329)* status: 1 of 58 files reviewed, 7 unresolved discussions (waiting on @juagargi and @matzf)

___
*[scionlab/models/core.py, line 137 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MN2ao8R0UqENburThtl:-MN3AeLb40VI0bmv2jry:bzd3cc2) ([raw file](https://github.com/netsec-ethz/scionlab/blob/9f0d7330202d1950448516b57ee1cda93152d96a/scionlab/models/core.py#L137)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This now misses certificate updates to all the other core ASes on the TRC bump, right? 
</blockquote></details>

That's correct. Since every core AS certificate is self signed, I don't see necessary to generate any other certificate before creating the TRC. Am I missing a case?
___
*[scionlab/models/trc.py, line 184 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MN2u2PEAsNV5jpfv8ZT:-MN3iajJ2pOcyIxqJyvN:b-ko8pv1) ([raw file](https://github.com/netsec-ethz/scionlab/blob/9f0d7330202d1950448516b57ee1cda93152d96a/scionlab/models/trc.py#L184)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Wouldn't it be more natural to make `signatures` a relation to `Key` here? It's the key that signs, not the certificate.  Perhaps the same applies to `votes`, but I'm not sure.
</blockquote></details>

It seems the TRC refers to the certificate serial number in the signatures.
We also pass the certificate (along with the key) to sign.

But just to clear out doubts, I created a test `test_scion_trcs:TRCCreationTests.test_sign_other_certificate` where I hopefully show that the certificate has to be the same one. PTAL at the test.
___
*[scionlab/scion/trcs.py, line 273 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MN2kOHUDC33hNJP76qZ:-MN33pI40RUiSzA-movV:b-376vyo) ([raw file](https://github.com/netsec-ethz/scionlab/blob/9f0d7330202d1950448516b57ee1cda93152d96a/scionlab/scion/trcs.py#L273)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Please don't `chdir` here, this could be executed concurrently. Instead, set `cwd=` in `subprocess.run`.
</blockquote></details>

Done. Good catch!
___
*[scionlab/scion/trcs.py, line 290 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MN2vUWC2vOUZm1YVUxy:-MN3AQ1dAyb9NV5jDMtA:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/9f0d7330202d1950448516b57ee1cda93152d96a/scionlab/scion/trcs.py#L290)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

The purpose function seemed clearer before: return the `int` timestamp, working around the fact that `timestamp` on "naive" datetimes defaults to local time.
Just call this in `_get_conf` instead of directly using `timestamp`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-26 14:47 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/329)* status: 1 of 58 files reviewed, 3 unresolved discussions (waiting on @juagargi and @matzf)

___
*[scionlab/models/core.py, line 137 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MN2ao8R0UqENburThtl:-MN3zGct97NdkNUcBl11:be63kp1) ([raw file](https://github.com/netsec-ethz/scionlab/blob/9f0d7330202d1950448516b57ee1cda93152d96a/scionlab/models/core.py#L137)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

That's correct. Since every core AS certificate is self signed, I don't see necessary to generate any other certificate before creating the TRC. Am I missing a case?
</blockquote></details>

Makes sense, sorry I was still thinking of certificates referring to a TRC version.
___
*[scionlab/scion/trcs.py, line 290 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MN2vUWC2vOUZm1YVUxy:-MN4-mFD9NOwazBE7sL_:b5jih9j) ([raw file](https://github.com/netsec-ethz/scionlab/blob/9f0d7330202d1950448516b57ee1cda93152d96a/scionlab/scion/trcs.py#L290)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Now it's just replacing the timezone  somewhere and the context on _why_ is gone. Whatever, i guess.


<!-- Sent from Reviewable.io -->

2020-11-26 15:11 UTC, matzf reviewed
> Reviewed 7 of 57 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/329)* status: 8 of 58 files reviewed, 6 unresolved discussions (waiting on @juagargi and @matzf)

___
*[scionlab/fixtures/testdata.py, line 36 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MN43B6z0hKOrnVr7fVs:-MN43B6z0hKOrnVr7fVt:butenw4) ([raw file](https://github.com/netsec-ethz/scionlab/blob/38b725c2be63dbb3741a883cc9cfc96d239ad760/scionlab/fixtures/testdata.py#L36)):*
> ```Python
>         testuser.create_testusers()
>         testtopo.create_testtopo()
>         testuseras.create_testuserases()
> ```

As discussed; this construction here with patching things to make the fixture generation deterministic seems to have become a bit of a monster, as openssl doesn't want to be told to be deterministic. 
This does not seem to be worth the benefits any longer. We've agreed to remove this entire patchy patchy patchwork and accept that generating the testdata fixture is not deterministic.
___
*[scionlab/models/core.py, line 304 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MN45TdwA0X92aa2oleA:-MN45TdwA0X92aa2oleB:b-85lskh) ([raw file](https://github.com/netsec-ethz/scionlab/blob/38b725c2be63dbb3741a883cc9cfc96d239ad760/scionlab/models/core.py#L304)):*
> ```Python
> 
>         for isd in isds:
>             isd.update_trc_and_certificates()
> ```

This function seems to be recreating the keys twice now -- once here (only the core keys) and once in `update_trc_and_certificates` which calls `update_keys_certs`. Perhaps `update_trc_and_certificates` should only call `update_certs` (which doesn't exist, but you know what I mean).
___
*[scripts/create-fixture-testdata.sh, line 36 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MN42yWX9B48ShKDq2K8:-MN42yWZ-tgp4cM57Sy3:b-y874hr) ([raw file](https://github.com/netsec-ethz/scionlab/blob/38b725c2be63dbb3741a883cc9cfc96d239ad760/scripts/create-fixture-testdata.sh#L36)):*
> ```Shell
> # TODO(juagargi) do we still need this sorting procedure?
> # # fixup jsonfield order
> # python scripts/sort-json-fields.py scionlab/fixtures/testdata.yaml
> ```

Nope, drop it.


<!-- Sent from Reviewable.io -->

2020-11-26 16:41 UTC, juagargi reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/329)* status: 8 of 58 files reviewed, 6 unresolved discussions (waiting on @juagargi and @matzf)

___
*[scionlab/scion/trcs.py, line 149 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MN2lvov3x_BteCityOk:-MN3q_BE6ViDkS2ClMl8:b-j0g62e) ([raw file](https://github.com/netsec-ethz/scionlab/blob/9f0d7330202d1950448516b57ee1cda93152d96a/scionlab/scion/trcs.py#L149)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Are there such nested calls? If so, why?
Anyway, I find this `configure` contextmanager and its use is a bit unnatural to read, to be honest. I would like to suggest to  implement a single entry point on `TRCConfig`:
```py
def generate(self: TRCConfig) -> bytes
  with TemporaryDirectory() as temp_dir:
    self.dump_certificates_to_files(temp_dir)   # preferrably, change this to _return_ the certificates (mutable state is hard to follow)
    self.gen_payload(temp_dir)
    signed_payload = ... 
    return conf.combine(temp_dir)
```

Or, even better, implement all these steps in a single entry point `generate()` on `TRCConfig`.

</blockquote></details>

There is already `scion.trcs.generate_trc` that does exactly that as a free function.
But you are right, the TRCConf doesn't need the context manager. I've changed it to follow your suggestion.
___
*[scionlab/scion/trcs.py, line 290 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MN2vUWC2vOUZm1YVUxy:-MN4QQUr-Cn3ifdjDlBj:bjh1jm9) ([raw file](https://github.com/netsec-ethz/scionlab/blob/9f0d7330202d1950448516b57ee1cda93152d96a/scionlab/scion/trcs.py#L290)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Now it's just replacing the timezone  somewhere and the context on _why_ is gone. Whatever, i guess.
</blockquote></details>

I added a message in the assertion. Let's make sure this is clear, or we (at least I) will forget why we do it.


<!-- Sent from Reviewable.io -->

2020-11-26 20:10 UTC, juagargi reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/329)* status: 8 of 58 files reviewed, 6 unresolved discussions (waiting on @juagargi and @matzf)

___
*[scionlab/scion/trcs.py, line 156 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MN3j3zNEkWyZdM00dB1:-MN4Qh5pAZHWMLAfJWVG:b-w6a1ut) ([raw file](https://github.com/netsec-ethz/scionlab/blob/9f0d7330202d1950448516b57ee1cda93152d96a/scionlab/scion/trcs.py#L156)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Here and in many many other places: writing a file like this can be shortened by using `pathlib.Path(...).write_text(...)`. There is also `write_bytes`, `read_text` and `read_bytes`.
The `pathlib.Path` constructor is also a convenient shortcut to `os.path.join`, e.g. `pathlib.Path(tmp_dir, self.CONFIG_FILENAME)`.
</blockquote></details>

This is fantastic, I'm very happy to have learnt about this. Thanks!


<!-- Sent from Reviewable.io -->

2020-11-26 21:05 UTC, juagargi reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/329)* status: 8 of 58 files reviewed, 6 unresolved discussions (waiting on @juagargi and @matzf)

___
*[scionlab/models/core.py, line 304 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MN45TdwA0X92aa2oleA:-MN5GHiU04gCr47jiZx5:bekiivr) ([raw file](https://github.com/netsec-ethz/scionlab/blob/38b725c2be63dbb3741a883cc9cfc96d239ad760/scionlab/models/core.py#L304)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This function seems to be recreating the keys twice now -- once here (only the core keys) and once in `update_trc_and_certificates` which calls `update_keys_certs`. Perhaps `update_trc_and_certificates` should only call `update_certs` (which doesn't exist, but you know what I mean).
</blockquote></details>

I just reviewed the original (in `develop`) one: it is also confusing: it creates keys for some ASes, but updates the certificates for all core ASes of any ISD that was "touched" by the new key generation.

I cannot make it update keys and certs only for the ases in the queryset, as they can be CAs of other non core ASes. So they have to trigger a full update on the ISD. That is, essentially, collecting which ISDs are involved in the queryset, and calling `update_trc_and_certificates`.

In any case, it is still left to cover the desired behavior with a test, so the intentions are clear at least there. Plus of course the comments that we already have.


<!-- Sent from Reviewable.io -->

2020-11-27 09:35 UTC, juagargi reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/329)* status: 7 of 60 files reviewed, 6 unresolved discussions (waiting on @juagargi and @matzf)

___
*[scionlab/fixtures/testdata.py, line 36 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MN43B6z0hKOrnVr7fVs:-MN82e1L2WR-toQSbNWX:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/38b725c2be63dbb3741a883cc9cfc96d239ad760/scionlab/fixtures/testdata.py#L36)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

As discussed; this construction here with patching things to make the fixture generation deterministic seems to have become a bit of a monster, as openssl doesn't want to be told to be deterministic. 
This does not seem to be worth the benefits any longer. We've agreed to remove this entire patchy patchy patchwork and accept that generating the testdata fixture is not deterministic.
</blockquote></details>

Done.
___
*[scripts/create-fixture-testdata.sh, line 36 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MN42yWX9B48ShKDq2K8:-MN7uRpn9H_NPGUObHJt:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/38b725c2be63dbb3741a883cc9cfc96d239ad760/scripts/create-fixture-testdata.sh#L36)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nope, drop it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-27 13:10 UTC, juagargi reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/329)* status: 2 of 64 files reviewed, 6 unresolved discussions (waiting on @matzf)

___
*[scionlab/models/trc.py, line 306 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MN2x_JjDoaeHO8n0ggr:-MN84mfIBj3ItZ7Gbwgu:b-6y457u) ([raw file](https://github.com/netsec-ethz/scionlab/blob/9f0d7330202d1950448516b57ee1cda93152d96a/scionlab/models/trc.py#L306)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I think we could do away with this custom through table. Ordering based on the `pk` should give use the same indices. And it would avoid the logic to set up these indices. What do you think?
</blockquote></details>

With the `pk` the order is not stable: adding more certificates to the TRC changes the indices of the existing ones.
But we don't need to reorder, as we don't add certificates to a TRC once it is created. I've removed the through model and refactored after it.


<!-- Sent from Reviewable.io -->

2020-11-27 19:59 UTC, juagargi reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/329)* status: 2 of 64 files reviewed, 6 unresolved discussions (waiting on @matzf)

___
*[scionlab/models/trc.py, line 306 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MN2x_JjDoaeHO8n0ggr:-MNAHLtdDYF2ujn6Hxar:b918uhe) ([raw file](https://github.com/netsec-ethz/scionlab/blob/9f0d7330202d1950448516b57ee1cda93152d96a/scionlab/models/trc.py#L306)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

With the `pk` the order is not stable: adding more certificates to the TRC changes the indices of the existing ones.
But we don't need to reorder, as we don't add certificates to a TRC once it is created. I've removed the through model and refactored after it.
</blockquote></details>

I was happy too soon: I had to add a commit just now to essentially make `TRC.certificates` immutable. TAL and check with care, for now to delete a certificate they must not be included in any TRC.


<!-- Sent from Reviewable.io -->

2020-12-02 12:39 UTC, matzf requested changes
> Reviewed 36 of 57 files at r1, 1 of 10 files at r3, 1 of 5 files at r6, 15 of 21 files at r7, 3 of 4 files at r8, 6 of 9 files at r9, 3 of 3 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/329)* status: 67 of 71 files reviewed, 25 unresolved discussions (waiting on @juagargi)

___
*[scionlab/migrations/0007_new_cppki.py, line 34 at r10](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNTvctcBksVSvraAxsG:-MNTvctcBksVSvraAxsH:baqmd4g) ([raw file](https://github.com/netsec-ethz/scionlab/blob/b2634deb6a50cf7ae78f33c1d5081f82e0b0b43c/scionlab/migrations/0007_new_cppki.py#L34)):*
> ```Python
>         isd.trcs.create()
>         # and validate
>         # TODO
> ```

Would this do for `create_as_pki`? Using an existing function, might mean fewer thing that could go wrong.

```python
for isd in ISD.objects.all():
  isd.update_trc_and_certificates()
```
___
*[scionlab/models/core.py, line 304 at r2](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MN45TdwA0X92aa2oleA:-MNU-opn3qPQdV4HpnLe:b-po3x06) ([raw file](https://github.com/netsec-ethz/scionlab/blob/38b725c2be63dbb3741a883cc9cfc96d239ad760/scionlab/models/core.py#L304)):*
> it is also confusing: it creates keys for some ASes, but updates the certificates for all core ASes of any ISD that was "touched" by the new key generation.

That was the intended behaviour. It's fine to re-issue a certificate for the same keys. After updating core keys for the selected ASes, we bumped the TRC version. A new version of the TRC meant new certificates for everything were required, as the certs would refer to the TRC version.

> I cannot make it update keys and certs only for the ases in the queryset, as they can be CAs of other non core ASes

We seem to be recording which certs are created by which CA, so it seems to be possible to only re-issue the affected certificates.
I'm perfectly happy with the full update, though.
___
*[scionlab/models/core.py, line 109 at r10](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNTzVJHDr-mCt9KjU-h:-MNTzVJIE4D4ttAs2HXR:b17h1k5) ([raw file](https://github.com/netsec-ethz/scionlab/blob/b2634deb6a50cf7ae78f33c1d5081f82e0b0b43c/scionlab/models/core.py#L109)):*
> ```Python
>         return self.update_trc()
> 
>     def update_trc(self):
> ```

Inline this to `update_trc_and_certificates`? Seems not to be called otherwise and would probably be a mistake to call it -- but it's a tempting function name to call.
___
*[scionlab/models/pki.py, line 46 at r10](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNU3F7mDOYkJp5DAl7a:-MNU3F7mDOYkJp5DAl7b:b3e3ph8) ([raw file](https://github.com/netsec-ethz/scionlab/blob/b2634deb6a50cf7ae78f33c1d5081f82e0b0b43c/scionlab/models/pki.py#L46)):*
> ```Python
>     votes = [0, 3] means the first and 4th certificate in the list of certificates from the
>     previous TRC). We need to preserve the possible voters in the previous TRCs, so making
>     the `certificates` effectively immutable.
> ```

_Now_ I understand this through relation thing :/
___
*[scionlab/models/pki.py, line 206 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNU5PVb8eh0WQZt2JHt:-MNU5PVb8eh0WQZt2JHu:b-crq5ap) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/models/pki.py#L206)):*
> ```
>             issuer_key = Key.objects.filter(AS__isd=subject.isd, AS__is_core=True).first()
>             issuer = issuer_key.AS if issuer_key else None
> ```
Why the detour over the `issuer_key`?
___
*[scionlab/models/pki.py, line 207 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNXgR_x9C857D0RxbjD:-MNXgR_x9C857D0RxbjE:b-9nkewy) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/models/pki.py#L207)):*
> ```Python
>             issuer_key = Key.objects.filter(AS__isd=subject.isd, AS__is_core=True).first()
>             issuer = issuer_key.AS if issuer_key else None
>         if issuer:
> ```

Shouldn't this just fail otherwise?
___
*[scionlab/models/pki.py, line 216 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNXfYll9B_T26EP3Lk5:-MNXfYll9B_T26EP3Lk6:byrip0w) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/models/pki.py#L216)):*
> ```Python
>                           self.create_voting_regular_cert,
>                           self.create_issuer_root_cert,
>                           self.create_issuer_ca_cert]]
> ```

Nit: not many characters saved, just make the list explicit:
```
        return [self.create_voting_sensitive_cert(subject, not_before, not_after),
                self.create_voting_regular_cert(subject, not_before, not_after),
                self.create_issuer_root_cert(subject, not_before, not_after),
                self.create_issuer_ca_cert(subject, not_before, not_after)]
```
___
*[scionlab/models/pki.py, line 239 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNXd0y5DR6g6hr7dH6h:-MNXd0y5DR6g6hr7dH6i:b37m31) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/models/pki.py#L239)):*
> ```Python
>         subject_key = subject.keys.latest(usage=Key.ISSUING_CA)
>         issuer_key = subject.keys.latest(usage=Key.ISSUING_ROOT)
>         not_before, not_after = validity(Validity(not_before, not_after), subject_key, issuer_key)
> ```

This validity computation is already included in the `_create_cert` function (same comment applies to `create_cp_as_cert` and `_create_self_signed_cert` below).
___
*[scionlab/models/pki.py, line 262 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNXdbTf3JCF3Pw4NoOi:-MNXdbTf3JCF3Pw4NoOj:bi7labx) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/models/pki.py#L262)):*
> ```Python
>         return self._create_cert(fcn, key, not_before, not_after)
> 
>     def _create_cert(self, fcn, subject_key, not_before, not_after, issuer_key=None):
> ```

Nit: order `issuer_key` right after `subject_key`. The default values is not needed, passing `None` explicitly in `_create_self_signed_cert` would improve readability.
___
*[scionlab/models/pki.py, line 349 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNX_Pa_D5Rf8yr6vuaf:-MNX_Pa_D5Rf8yr6vuag:b-6ikk4d) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/models/pki.py#L349)):*
> ```Python
>         AS certificates will return the whole chain: first the subject cert, then the issuer's one.
>         """
>         return self.certificate + (self.ca_cert.certificate if self.key.usage == Key.CP_AS else '')
> ```

Nit: seems unnecessarily terse;
```py
if self.key.usage == Key.CP_AS:
   return self.certificate + self.ca_cert.certificate 
else:
   return self.certificate
```
___
*[scionlab/models/trc.py, line 306 at r1](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MN2x_JjDoaeHO8n0ggr:-MNXjyj3AO2Q1zSDYpoE:b-osgus9) ([raw file](https://github.com/netsec-ethz/scionlab/blob/9f0d7330202d1950448516b57ee1cda93152d96a/scionlab/models/trc.py#L306)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

I was happy too soon: I had to add a commit just now to essentially make `TRC.certificates` immutable. TAL and check with care, for now to delete a certificate they must not be included in any TRC.
</blockquote></details>

Ok, sorry I didn't understand this well when I wrote the comment. Now I see the advantage of the through relation thing. I guess it's fine either way
___
*[scionlab/models/trc.py, line 66 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNXpZiFCYtNgx1wNvHG:-MNXm4Yt3uI5Cyq2Kbk6:b-fnblea) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/models/trc.py#L66)):*
> ```Pytho [...]

2020-12-02 12:45 UTC, matzf requested changes
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/329)* status: 67 of 71 files reviewed, 25 unresolved discussions (waiting on @juagargi and @matzf)

___
*[scionlab/scion/trcs.py, line 260 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNY-FyY7DJloJy0oQ9L:-MNYTsOiBwHNv_UIaBMa:bh9d6cs) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/scion/trcs.py#L260)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

The tool is called `scion-pki` so naming the related functions/variables "cppki" seems surprising.

Also, I'd suggest to combine the `_run_scion_cppki` and `_raw_run_scion_cppki` functions, using a `check` flag analogous to the subprocess interface:
```
def _run_scion_pki(*args, cwd=None, check=True):
  ret = subprocess.run([...], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=False, cwd=cwd, encoding='utf-8')
  if check and ret.returncode != 0:
     raise Exception(...)
  return ret
```
</blockquote></details>

Working
___
*[scionlab/tests/utils.py, line 540 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNYQJS04QqrdgYMCrbj:-MNYTLHyBvDlpxNEwuta:bh9d6cs) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/tests/utils.py#L540)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I think this would make more sense in `scionlab.scion.trcs`, as e.g. `verify_trc`. Then the test code can call this as `trcs.verify_trc(...)`. And I think this should take a list of TRCs.
</blockquote></details>

Working
___
*[static_bin/README.md, line 18 at r10](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNUF8TD--m3RKe9JN_O:-MNYTuG12UojeJAKJdve:bh9d6cs) ([raw file](https://github.com/netsec-ethz/scionlab/blob/b2634deb6a50cf7ae78f33c1d5081f82e0b0b43c/static_bin/README.md#L18)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I think we should be more specific here; we shouldn't only provide instructions but a rigirious process to (re-)create the checked in binaries. Preferrably we should have a Makefile/Docker/whatever that does _exactly_ what we want, including if possible a reference to the exact commit hash used.
</blockquote></details>

Working


<!-- Sent from Reviewable.io -->

2020-12-02 14:58 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/329)* status: 64 of 71 files reviewed, 23 unresolved discussions (waiting on @juagargi and @matzf)

___
*[scionlab/scion/trcs.py, line 260 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNY-FyY7DJloJy0oQ9L:-MNYxOA7DC8ev7Pz4aNU:bb6un1j) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/scion/trcs.py#L260)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Working
</blockquote></details>

Done
___
*[scionlab/tests/utils.py, line 540 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNYQJS04QqrdgYMCrbj:-MNYxQZ4-ECOBn_5PA1M:bb6un1j) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/tests/utils.py#L540)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Working
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2020-12-02 17:45 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/329)* status: 62 of 73 files reviewed, 21 unresolved discussions (waiting on @juagargi and @matzf)

___
*[static_bin/README.md, line 18 at r10](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNUF8TD--m3RKe9JN_O:-MNZYkqJ-QYMpRL06gl-:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/b2634deb6a50cf7ae78f33c1d5081f82e0b0b43c/static_bin/README.md#L18)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Working
</blockquote></details>

Done.
___
*[static_bin/README.md, line 27 at r10](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNUEty_EId9mEccrRLp:-MNZYlnp4hVbMnPt7hqC:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/b2634deb6a50cf7ae78f33c1d5081f82e0b0b43c/static_bin/README.md#L27)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This command misses the (crucial) git information (some magic -X variable on the go build command needed).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-02 17:49 UTC, matzf reviewed
> Reviewed 5 of 9 files at r12, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/329)* status: 68 of 73 files reviewed, 21 unresolved discussions (waiting on @juagargi and @matzf)



<!-- Sent from Reviewable.io -->

2020-12-02 19:58 UTC, juagargi reviewed
> Reviewed 1 of 21 files at r7, 2 of 9 files at r9, 2 of 3 files at r10, 1 of 1 files at r11, 7 of 9 files at r12, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/329)* status: all files reviewed, 21 unresolved discussions (waiting on @juagargi and @matzf)

___
*[scionlab/models/pki.py, line 206 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNU5PVb8eh0WQZt2JHt:-MNZxz5R1BlK5a6M9V9e:b-3nm04y) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/models/pki.py#L206)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

> ```
>             issuer_key = Key.objects.filter(AS__isd=subject.isd, AS__is_core=True).first()
>             issuer = issuer_key.AS if issuer_key else None
> ```
Why the detour over the `issuer_key`?
</blockquote></details>

technically, we need an issuer (core AS) with a key. Core ASes without keys are non-valid, and should be excluded. Something like `AS.objects.filter(isd=subject.isd, is_core=True, keys__isnull=False)` should also work, but I have not tested it.
___
*[scionlab/models/trc.py, line 299 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNXmVWw9RKSWemjegcd:-MN_-P7S8t0V4cxrhDPO:bagm922) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/models/trc.py#L299)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Not sure where this documentation should go, but I find this function more confusing than helpful. I think a simple `if isd.trcs.exists()` would serve the same purpose and would be clearer.
</blockquote></details>

Yes, but let's not loose the documentation about the update conditions; and regular vs sensitive doc as well.
___
*[scionlab/scion/certs.py, line 191 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNXxXkaBuDOonGvgnNH:-MN_-gCJ0EvGyvnEm2XY:b-791smz) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/scion/certs.py#L191)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Btw. is there anything that we could reference as source for all of these settings? Documentation or scion source code?
</blockquote></details>

Hmm, there is the `scion-pki/testcrypto` package, where there are invocations to `openssl` with these. I am not certain that this is the only set of values acceptable: they are correct, but maybe incomplete.
___
*[scionlab/tests/test_trc.py, line 109 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNYOmFb9j_9SCgYvlPf:-MN_0rg83mBf01LlRnnH:b-8nid8l) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/tests/test_trc.py#L109)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This test case is super long. Can this be split into independent separate tests? Or does this need to be sequential? In that case, it might be 
</blockquote></details>

At the moment it is sequential. Parts of it will need to be sequential, as they are the updates. Other parts (in particular the "sanity checks") are not really needed in only one sequence.
___
*[static_bin/scion-pki, line  at r10](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNUFTi46sbnn4mYu2Nn:-MNZw7SNAw36DpiHQheg:bixe3qq) ([raw file](https://github.com/netsec-ethz/scionlab/blob/b2634deb6a50cf7ae78f33c1d5081f82e0b0b43c/static_bin/scion-pki#L)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Do we need to enable git-lfs for this? The binary is 27MB. :/
</blockquote></details>

Yes, let's enable it and rewrite history. Can you do it?


<!-- Sent from Reviewable.io -->

2020-12-03 08:23 UTC, matzf reviewed
> Reviewed 1 of 13 files at r14, 1 of 12 files at r15.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/329)* status: 63 of 74 files reviewed, 20 unresolved discussions (waiting on @juagargi and @matzf)

___
*[static_bin/scion-pki, line  at r10](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNUFTi46sbnn4mYu2Nn:-MNbfnQSCDOtY4UKZKut:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/b2634deb6a50cf7ae78f33c1d5081f82e0b0b43c/static_bin/scion-pki#L)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Yes, let's enable it and rewrite history. Can you do it?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-03 11:00 UTC, matzf reviewed
> Reviewed 8 of 12 files at r15.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/329)* status: 71 of 74 files reviewed, 7 unresolved discussions (waiting on @juagargi and @matzf)

___
*[scionlab/models/core.py, line 109 at r10](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNTzVJHDr-mCt9KjU-h:-MNbjzgGDeEtH-rY48Q3:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/b2634deb6a50cf7ae78f33c1d5081f82e0b0b43c/scionlab/models/core.py#L109)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Inline this to `update_trc_and_certificates`? Seems not to be called otherwise and would probably be a mistake to call it -- but it's a tempting function name to call.
</blockquote></details>

Done.
___
*[scionlab/models/pki.py, line 206 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNU5PVb8eh0WQZt2JHt:-MNbtZ9C3W1_mn6eRA0f:bkd039u) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/models/pki.py#L206)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

technically, we need an issuer (core AS) with a key. Core ASes without keys are non-valid, and should be excluded. Something like `AS.objects.filter(isd=subject.isd, is_core=True, keys__isnull=False)` should also work, but I have not tested it.
</blockquote></details>

There shouldn't be core ASes without keys, right? Otherwise, this will just fail with `Key.DoesNotExist` when fetching the key, which seems ok.
Done.
___
*[scionlab/models/pki.py, line 207 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNXgR_x9C857D0RxbjD:-MNbw3F696ddeKyRh1YD:b-llyz5o) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/models/pki.py#L207)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Shouldn't this just fail otherwise?
</blockquote></details>

Done, will now raise `AS.DoesNotExist` if no core AS can be found.
Note: creating ASes without core ASes was apparently previously possible, as some test cases triggered this in their setup. Updated these testcases to either avoid the certificate creation or create a core AS first.
___
*[scionlab/models/pki.py, line 216 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNXfYll9B_T26EP3Lk5:-MNbu6OM0kflEUT7mUzS:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/models/pki.py#L216)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit: not many characters saved, just make the list explicit:
```
        return [self.create_voting_sensitive_cert(subject, not_before, not_after),
                self.create_voting_regular_cert(subject, not_before, not_after),
                self.create_issuer_root_cert(subject, not_before, not_after),
                self.create_issuer_ca_cert(subject, not_before, not_after)]
```
</blockquote></details>

Done.
___
*[scionlab/models/pki.py, line 239 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNXd0y5DR6g6hr7dH6h:-MNbvs5sE3MrYiKmF0KW:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/models/pki.py#L239)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This validity computation is already included in the `_create_cert` function (same comment applies to `create_cp_as_cert` and `_create_self_signed_cert` below).
</blockquote></details>

Done.
___
*[scionlab/models/pki.py, line 262 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNXdbTf3JCF3Pw4NoOi:-MNbvtDL6lVFq2B5GEoA:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/models/pki.py#L262)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit: order `issuer_key` right after `subject_key`. The default values is not needed, passing `None` explicitly in `_create_self_signed_cert` would improve readability.
</blockquote></details>

Done.
___
*[scionlab/models/pki.py, line 349 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNX_Pa_D5Rf8yr6vuaf:-MNbw1Q3-NPHnNtae421:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/models/pki.py#L349)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit: seems unnecessarily terse;
```py
if self.key.usage == Key.CP_AS:
   return self.certificate + self.ca_cert.certificate 
else:
   return self.certificate
```
</blockquote></details>

Done.
___
*[scionlab/models/trc.py, line 66 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNXpZiFCYtNgx1wNvHG:-MNc9CH32arHvuGOXE9C:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/models/trc.py#L66)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

`if _can_regular_update(...)` ?
</blockquote></details>

Done.
___
*[scionlab/models/trc.py, line 207 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNXqE8h552Wcfz-ldaK:-MNc9Bir3f_2SGJU-728:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/models/trc.py#L207)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

> ```
> get_certificates
> ```
Inline this in `get_certificate_indices` for clarity.
</blockquote></details>

Done.
___
*[scionlab/models/trc.py, line 227 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNXgayWAeKqFm5rxMWx:-MNc9Iye4nP5K3WxRTzK:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/models/trc.py#L227)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit: `__str__` should go right after `Meta` (django convention, https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/#model-style). 
</blockquote></details>

Done.
___
*[scionlab/models/trc.py, line 235 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNXp8vMDexKYIE9M4UE:-MNc9KRH-etmbwlEYY_z:b-mbu6bo) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/models/trc.py#L235)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Maybe `check_regular_update_impossible` so that it's a little bit clearer that this is for tests?
</blockquote></details>

Done. Still feels clunky. Perhaps it would've been better to move this to the tests directly, or raise an exception on error.
___
*[scionlab/models/trc.py, line 299 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNXmVWw9RKSWemjegcd:-MNc5zEaBgMki9OAWxGx:b-4uvuxz) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/models/trc.py#L299)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Yes, but let's not loose the documentation about the update conditions; and regular vs sensitive doc as well.
</blockquote></details>

Done. Shuffled the docs around a bit.


<!-- Sent from Reviewable.io -->

2020-12-03 14:31 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/329)* status: 63 of 76 files reviewed, 4 unresolved discussions (waiting on @juagargi and @matzf)

___
*[scionlab/scion/keys.py, line 43 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNXyLiXCJussY8vBNfG:-MNcpEHm43wMtS6zvOol:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/scion/keys.py#L43)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

For `encode_key` and `decode_key`, it would be more convenient to return / take a string instead of bytes.
</blockquote></details>

Done.
___
*[scionlab/scion/keys.py, line 45 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNXyiij80axWp1tuFZ1:-MNcpF8U4CDIGiKlkJh6:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/scion/keys.py#L45)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

According to the docs, the `default_backend()` is implicit (with cryptography >= 3.1).
</blockquote></details>

Done.
___
*[scionlab/tests/test_trc.py, line 109 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNYOmFb9j_9SCgYvlPf:-MNd-Oi_ALl_tefIdy_W:b-mxwzeg) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/tests/test_trc.py#L109)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

At the moment it is sequential. Parts of it will need to be sequential, as they are the updates. Other parts (in particular the "sanity checks") are not really needed in only one sequence.
</blockquote></details>

I don't like it but we'll keep it for now. No time right now -- and cleanup is easy, just remove the tests ;).


<!-- Sent from Reviewable.io -->

2020-12-03 15:17 UTC, matzf reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/329)* status: 62 of 76 files reviewed, all discussions resolved (waiting on @juagargi and @matzf)

___
*[scionlab/migrations/0007_new_cppki.py, line 34 at r10](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNTvctcBksVSvraAxsG:-MNd1f7i3b3Ymc76blzv:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/b2634deb6a50cf7ae78f33c1d5081f82e0b0b43c/scionlab/migrations/0007_new_cppki.py#L34)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Would this do for `create_as_pki`? Using an existing function, might mean fewer thing that could go wrong.

```python
for isd in ISD.objects.all():
  isd.update_trc_and_certificates()
```
</blockquote></details>

Done.
___
*[scionlab/models/trc.py, line 209 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNXr7jE34kMbnZr7qbt:-MNd2jdM1uqTfwM0sYxE:b-kqslow) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/models/trc.py#L209)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

> ```
> get_voters_indices
> ```
This not used, only tested. Shouldn't we test `get_certificate_indices` directly instead?
</blockquote></details>

Done, moved to test code.
___
*[scionlab/scion/certs.py, line 43 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNXwPK47Z_6ms4CBvi-:-MNdAR8U90PM-HtXWWha:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/scion/certs.py#L43)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Perhaps it would be somewhat more readable to use named tuples for the extensions, unless things get overly verbose. The `typing.NamedTuple` is quite nice! 
</blockquote></details>

Done.
___
*[scionlab/scion/certs.py, line 191 at r11](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-MNXvyPh29gVkdDZAbBZ:-MNdASDU-ZfbH9-F3wJq:b-896fix) ([raw file](https://github.com/netsec-ethz/scionlab/blob/aa031f2f311da08ffb3e4349fa32a5736fa3bd97/scionlab/scion/certs.py#L191)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I know this will make this code unpleasantly verbose, but could we use named parameters here for `BasicConstraints`,`KeyUsage`, etc? Looking at this without reference documentation, it just means nothing...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-03 16:09 UTC, juagargi reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 57 files at r1, 3 of 21 files at r7, 1 of 4 files at r8, 1 of 13 files at r14, 4 of 12 files at r15, 11 of 13 files at r16.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-:-MNdML3H0VH4Qw3DaqXY:bnfp4nl)* status: 74 of 76 files reviewed, all discussions resolved (waiting on @juagargi)



<!-- Sent from Reviewable.io -->

2020-12-03 16:09 UTC, juagargi reviewed
> Reviewed 2 of 13 files at r16.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/329)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-03 16:43 UTC, juagargi reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r17.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-:-MNdU3b30TiHagNDB42J:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-03 16:55 UTC, matzf approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 9 of 13 files at r16.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/329#-:-MNdWnHF7wxUa6UcBKC3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @juagargi)



<!-- Sent from Reviewable.io -->

2020-12-03 17:15 UTC, merged